atlassian-api/atlassian-python-api

atlassian/__init__.py
atlassian/bamboo.py

Hi,
I had to play with Bamboo last days, and i just decided to extend your library a little.
Could you review and merge if everything is okay?
Thanks in advance!

Bamboo support

---

atlassian/bamboo.py

This is a bit OCD, but I hate seeing my IDE (pyCharm) flagging this :)

Make Bamboo variable names PEP8-compliant

---

atlassian/confluence.py
atlassian/rest_client.py

This PR allows attaching files to pages. 
I hope you find this PR useful. 
Tested like this
--------------------
```
confluence = Confluence(
url='https://company.atlassian.net/wiki/',
username='username',
password='password')
title='testPage'
space='TST'
confluence.get_page_by_title(space=space,title=title)
confluence.attach_file(title=title, space=space, filename='example-image.jpg')
```
with local file: `example-image.jpg`

Implement attach files

---

.travis.yml
atlassian/jira.py

Hi! 
I have added a new method. 
For fix use case, like generate the report who can be assignable on project. 
It is need for the security audit.
Cheers,

 Provide assignable users for project

---

atlassian/confluence.py
atlassian/rest_client.py
examples/confluence-draft-page-cleaner.py
examples/confluence-trash-cleaner.py

Hi! 
This PR based on feedback from https://community.atlassian.com/t5/Confluence-articles/How-to-clean-programmatically-old-drafts-and-purge-trash-with/ba-p/876791
Thanks
Cheers,

Confluence cleaner updates

---

atlassian/confluence.py

Method to get the page_id if we have the title of the pge, parent page id and space name

Method to get the page_id if we have the title of the pge, parent page id and space name

---

atlassian/service_desk.py
docs/service_desk.rst

Added 
- get service desks
- get customers transitions
Updated
- get_organizations fix
- service desk docs

New features and fix

---

atlassian/confluence.py
examples/jira-create-issue.py

Hi! 
This one example how to create the Jira case and new Confluence method
Cheers,

Yet another example and one method for Confluence

---

atlassian/jira.py
atlassian/service_desk.py
docs/jira.rst
docs/service_desk.rst

Changed: add_attachment function for Jira module
Added: New attachments functions for Jira Service Desk module
Updated: Description for new functions was add to docs

Added new functions. Updated docs.

---

README.rst
atlassian/service_desk.py
docs/service_desk.rst

Updated: Description for new functions was add to docs

Added: SLA actions for Jira Service Desk module

---

atlassian/rest_client.py

Hi! 
It is the fix for url joiner method.
Before it does not work with context properly.
Cheers,

Bugfix for rest client  in url joiner method. 

---

atlassian/confluence.py

Hi! 
This is a newmethod for detect unknown attachements error. 
Cheers,

Check unknown attachments error

---

atlassian/service_desk.py
docs/service_desk.rst

Updated: Description for new functions was add to docs

Added: Manage Organizations actions for Jira Service Desk module

---

CONTRIBUTING.rst
docs/service_desk.rst

Updated: New mandatory conditions for contributors.

---

atlassian/bitbucket.py

Hi! 
this is bugfix for get_tags method in bitbucket module.
Also, I have added a log messages 
Cheers,

Set the start parameter and the log info messages

---

atlassian/bitbucket.py
atlassian/confluence.py
examples/jira-tempo-account-customers.py

Hi! 
I hope this parameters will help you for fix #104 
Cheers,
Tsymzhitov Gonchik

Confluence CQL  parameters

---

atlassian/bitbucket.py
atlassian/confluence.py
examples/jira-tempo-account-customers.py

Hi! 
This commit related polishing like static method, doc updates etc.
Cheers,

Polish release

---

examples/confluence-search-cql.py

Hi! 
This is example for show how to work with cql #101  
Cheers,

Add confluence search example

---

atlassian/service_desk.py
docs/service_desk.rst

Updated: Added new methods description

Added: New methods for Jira Service Desk module (manage a participants)

---

atlassian/service_desk.py
docs/service_desk.rst

Updated:
- get_organizations method. Now you can get list of all organizations or list of organizations from one Service Desk
- Update docs. Add description for new methods. Update description for the get_organizations method
Fixed: Description in docs

Added: New methods for manage organizations

---

atlassian/service_desk.py
docs/service_desk.rst

Updated: Added description for new methods

Added: New methods for approvals

---

atlassian/jira.py
atlassian/rest_client.py
docs/jira.rst

Updated:
- Docs (added description for new methods)
- REST Client (added 'params' argument into DELETE method)

New functionality added: Added new methods for Jira module

---

atlassian/jira.py
atlassian/rest_client.py
docs/jira.rst

Updated:
- Docs (added description for new methods)
- REST Client (added 'params' argument into POST method)

Added: New methods for Jira module (managing users in groups)

---

examples/confluence-page-versions-cleaner.py

Hi! 
Example how to clean page versions from customer facing Confluences
Cheers,

Confluence: page version cleaner example

---

atlassian/rest_client.py

Obscured password in logging output.

---

atlassian/bitbucket.py
atlassian/confluence.py
atlassian/jira.py

Hi! 
This is more refactoring release. 
Cheers,

Refactoring PR

---

atlassian/jira.py

A new method for update user properties for jira
Cheers,

Update the user attributes

---

atlassian/bitbucket.py
examples/bitbucket-fork-repository.py

this feature is very useful in our environment. 
We fork a Template Repository to a new repository we work with.

new feature: fork repository

---

atlassian/service_desk.py
docs/service_desk.rst

Updated functions in Service Desk module.
Updated docs.

Added new methods for Service Desk module.

---

atlassian/confluence.py

PRs for 
https://github.com/atlassian-api/atlassian-python-api/issues/149 and 
https://github.com/atlassian-api/atlassian-python-api/issues/150

Issues 149 and 150

---

atlassian/bitbucket.py
docs/bitbucket.rst

Bitbucket create and branch

---

atlassian/service_desk.py
docs/service_desk.rst

enable raiseOnBehalfOf in customer requests

ServiceDesk: specify author of request

---

atlassian/bitbucket.py
docs/bitbucket.rst

Bitbucket: added create method for project

---

atlassian/bitbucket.py
docs/bitbucket.rst

Added new methods for branching model, docs updated (example in [docs](https://github.com/atlassian-api/atlassian-python-api/blob/bef94b43194dfc56d1530aa9861d221aaef7f2fa/docs/bitbucket.rst#manage-repositories)).

Bitbucket: added enable, disable, get, set methods for branching model

---

atlassian/bitbucket.py
docs/bitbucket.rst

I added some API calls for Bitbucket. It could be useful for others

Extend bitbucket API

---

atlassian/__init__.py
atlassian/marketplace.py
setup.cfg

Add marketplace api for investigate situation with that,

Add MarketPlace Api

---

atlassian/confluence.py

New method add_comment. There is an option to add a comment to Jira, why not make the option to add a comment to the wiki?

Ability to add a comment

---

atlassian/bitbucket.py

Signed-off-by: Martin Rakovec <martin.rakovec@comap-control.com>

Bibucket: Fix reading empty response for some methods

---

atlassian/jira.py

Check UPM status

---

atlassian/__init__.py
atlassian/jira8.py
docs/jira8.rst

Added new Jira 8 experimental module.

---

atlassian/jira8.py

- Application roles
- Attachments

Added new Jira 8 methods:

---

atlassian/confluence.py
docs/confluence.rst
examples/confluence-export-page.py

Fixes Issue 199
https://github.com/atlassian-api/atlassian-python-api/issues/199

Added functionality to export PDF from Confluence Cloud

---

atlassian/bitbucket.py
docs/bitbucket.rst

The implemented method allows to grant project permissions to an specified user

Implemented new bitbucket project method

---

atlassian/bitbucket.py
docs/bitbucket.rst

The implemented method allows to grant repository permissions to an specified user

Implemented new bitbucket repository method

---

atlassian/jira.py

Jira: Sprint related methods

---

atlassian/jira.py

It is better to close the task by ID, the status name can be changed :(

Add set_issue_status_by_id

---

atlassian/jira.py

Tempo related methods

---

atlassian/bamboo.py
examples/bamboo-plan-directory-info.py

For the link to the Atlassian documentation, look at the function description

Bamboo: add method for plan directory information + example 

---

atlassian/confluence.py
atlassian/jira.py

Polish and new method to remove page versions

---

atlassian/jira.py
atlassian/jira8.py
atlassian/rest_client.py

Added new Jira 8 methods:
- Delete issue
- Edit issue
- Get issue
Updated:
- Create issue method
- rest_client PUT method

Additions and updates.

---

atlassian/bamboo.py

Yes, I needed to do 4 commits to fix the incorrect variable name. =(

Fix incorrect variable name

---

atlassian/jira.py

the expand parameter is added to get more information for the JQL search,  e.g. issue change histories

add expand to jql

---

atlassian/jira.py

Tempo methods

---

atlassian/jira.py

Signed-off-by: Mamh-Linux <bright.ma@blackshark.com>

add one new method to get issue all fields

---

README.rst
atlassian/bitbucket.py

Bitbucket: markup preview method

Bitbucket: markup preview method

---

README.rst
atlassian/jira.py
docs/conf.py
docs/index.rst
docs/jira.rst

Updated: docs, README, docs downloads icon

Added: get issue security schemes methods, docs icon

---

docs/confluence.rst

update arguments in Documentation for 'get_all_pages_from_space' and 'get_all_pages_from_space_trash' for version atlassian-python-api-1.13.24

update docs for get_all_pages_from_space* to 1.13.24

---

atlassian/confluence.py

Fix #307 (get_pages_by_label)

---

atlassian/jira.py

All sprint with status

---

atlassian/confluence.py

Confluence: method for avatars

---

atlassian/bitbucket.py
docs/bitbucket.rst

Hi, I had been using this GET call to automatize some Bitbucket tasks and I've included in this library to simplify my python scripts... I hope you would considered to merge this PR :)

New Bitbucket method - List repositories in a project

---

atlassian/bitbucket.py

Bitbucket api methods

---

examples/jira-add-components-to-all-projects.py

Added a new example for JIRA that :
* loops over each projects
* creates a component datastructure with the minimal informations required
* create the components in each projects (same list of components)

New example added 

---

atlassian/confluence.py

whitesource

---

atlassian/bitbucket.py

Added get and set repo settings functions. 
I am considering more specific functions, but figured I would start here and get feedback.

added get/set repo settings

---

atlassian/bitbucket.py

made repository optional
added 'all_branches_permissions'

branches_permissions

---

atlassian/bamboo.py

Equivalent to the "Stop Build" button in GUI

new method added to stop build which is in progress

---

atlassian/bamboo.py

Bamboo add stop build

---

.travis.yml

CI build for the current Python version.

Python 3.8 CI build

---

atlassian/confluence.py

I don't know if this change makes sense but I was using your api and a method was useful to add stuff to the beginning of an existing page similar to append. Therefore I made it. I considered having it as a flag on append method and make it possible to append on top of page. I can do it like that if it makes more sense

Add append option to the begining of the page

---

atlassian/bitbucket.py
docs/bitbucket.rst

Create standar methods get, create, update and delete conditions (reviewers) for projects and repositories for Bitbucket API

Added default reviewers methods for Bitbucket API

---

atlassian/jira.py

Signed-off-by: weiyang <weiyang.ones@gmail.com>

[jira] Fix 'issue_exists'/'issue_deleted'

---

atlassian/confluence.py

[Confluence] Allow adding comments to page history version on update

---

atlassian/bitbucket.py

Added function to **get the build statuses associated with a commit**.

function to get the build statuses

---

atlassian/bamboo.py
atlassian/confluence.py
examples/bamboo/bamboo-remove-unknown-status-build-results.py
examples/confluence/confluence-page-versions-cleaner.py

Fix for  #463
And a few examples for Bamboo Jobs

Bamboo examples and Confluence fix of params

---

atlassian/bamboo.py
atlassian/confluence.py
examples/bamboo/bamboo-label-based-cleaner.py
examples/bamboo/bamboo-remove-old-failed-results.py
examples/bamboo/bamboo-remove-unknown-status-build-results.py
examples/confluence/confluence-page-versions-cleaner.py

Example to delete build results

Bamboo examples

---

atlassian/bitbucket.py
docs/bitbucket.rst

#471 
Add the ability of deleting a Pull Request.
`atlassian.bitbucket.Bitbucket.delete_pull_request`
I also fix indentation in the documentation.

[Bitbucket] Delete a pull request

---

atlassian/bitbucket.py
examples/bitbucket/bitbucket-pullrequest-tasks.py

…regular task to the comment using comment id)

Added: get_tasks, add_task

---

atlassian/confluence.py
docs/confluence.rst

create_page created a page using the old editor, this PR adds the option to use the v2 editor

Add the v2 editor as an option to the create_page function

---

atlassian/bitbucket.py
docs/bitbucket.rst

Implementation of parts of the [issues](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/issues/%7Bissue_id%7D) REST API.

Wrappers for Bitbucket Issues REST API

---

atlassian/jira.py

My big important changes after long reviewing code during the quarantine

Modify get_issue fields param to use either list or string value

---

docs/index.rst

Adds instructions to authenticate to the Cloud APIs.

Update index.rst - Cloud API connection example

---

atlassian/bitbucket.py
docs/bitbucket.rst

This will come as a huge surprise, but after being able to read repository labels, it would be nice to be able to set them as well :-)

Add ability to set a label on a repository via the API

---

atlassian/rest_client.py

Enhanced a bugfix where json import was getting overwritten due to json argument in request api.

Fixed bug where json import was getting overridden with argument

---

atlassian/jira.py
docs/jira.rst

- Addition of the parameter change to invoke jql with change in parameters
- Added the relevant changes in doc file also
Closes #537

Addition of parameters for start & limit in the function of `get_all_project_issues`

---

CONTRIBUTING.rst

for raising PR with service name prefixed such as [JIRA] or [CONFLUENCE] identifying which service fix
Help the reviewer and log viewers to associate the feature is for which service

Contribution guidelines addition towards PR generation with good commit message Headers

---

atlassian/confluence.py

Get info from https://docs.atlassian.com/atlassian-confluence/1000.73.0/com/atlassian/confluence/plugins/restapi/resources/TemplateResource.html

[Confluence] Add methods for templates. Experimental API

---

atlassian/rest_client.py

Hey, 
I've thought we can add 2 essential things to the atlassian rest client, for enhancing the implementation.
The internal session (`requests.Session`) should be closed after its usage. When closing the session, its adapters are closed. It is a good practice to close the session after we finish using it. 
Therefore, I've added the `close` method, for supporting closing the client, which will close the internal session of the client (for those who care about that).
In order to make it idiomatic, we can support the context mangers API, so that the following code will be valid:
```python
with Jira(url, username, password) as jira:
```
Thanks to the context managers API, the session will be closed at the end of the block. In order to support it, we should implement the magic methods …

Atlassian Rest Client: Enhancing Implementation

---

atlassian/jira.py

Add filter functionality and experimental functionalities for attachment and comment properties

[Jira] Add filter functionality and experimental functionalities 

---

atlassian/jira.py
docs/jira.rst

Bugfix: pass parameters to query string i.o. request data.
Add additional parameters.

Jira: add parameters to query string i.o. request data.

---

atlassian/bitbucket.py

[BitBucket] Fix double url in repo_all_list

---

atlassian/bitbucket/__init__.py
atlassian/bitbucket/base.py
atlassian/bitbucket/cloud/__init__.py
atlassian/bitbucket/cloud/base.py
atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/bitbucket/cloud/repositories/branchRestrictions.py
atlassian/bitbucket/cloud/repositories/defaultReviewers.py
atlassian/bitbucket/cloud/repositories/issues.py
atlassian/bitbucket/cloud/repositories/pipelines.py
atlassian/bitbucket/cloud/workspaces/__init__.py
atlassian/bitbucket/cloud/workspaces/projects.py
atlassian/jira.py
atlassian/rest_client.py
docs/bitbucket.rst
examples/bitbucket/bitbucket_cloud_oo.py
requirements.txt
setup.py

First apporach of implementing a OO interface as mentioned in #610.
The default reviewers are only readable. I use the same credentionals as in the web interface where I can create a default reviewer.
closes #610

[Bitbucket] First approach for object oriented interface for bitbucket cloud.

---

atlassian/confluence.py

There is no status method in the response message

There is no status method in the response message

---

.dockerignore
.gitbugtraq
.github/workflows/test.yml
.travis.yml
CONTRIBUTING.rst
Dockerfile.qa
Makefile
atlassian/bitbucket/__init__.py
atlassian/bitbucket/base.py
atlassian/bitbucket/cloud/__init__.py
atlassian/bitbucket/cloud/base.py
atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/bitbucket/cloud/repositories/branchRestrictions.py
atlassian/bitbucket/cloud/repositories/defaultReviewers.py
atlassian/bitbucket/cloud/repositories/issues.py
atlassian/bitbucket/cloud/repositories/pipelines.py
atlassian/bitbucket/cloud/workspaces/__init__.py
atlassian/bitbucket/cloud/workspaces/projects.py
atlassian/jira.py
atlassian/rest_client.py
examples/bitbucket/bitbucket_cloud_oo.py
examples/jira/jira-issues-csv-export.py
requirements-dev.txt

Apply style changes from black test.
In my opinion the Github actions shall be marked as required merge check to keep styling clean.
Test is running on my fork with a test PR (https://github.com/Spacetown/atlassian-python-api/pull/1).
closes #616

[TestFramework] Add docker image and Github action.

---

atlassian/service_desk.py

I would like to attach multiple files to an issue without spamming the comment section.
The change proposes to use a list instead of a string, but has some backwards compability.
As far as I know, there are better checks for iterables (while excluding strings). If necessary I can add that (or is there somewhere already a function that can do that?).
Best regards

[ServiceDesk] Support multiple attached files for a single comment

---

atlassian/bitbucket/__init__.py

…159bcf98992a4bb892a2fb4ad8090c3bd836

[BitBucket]: fixing work with comments

---

atlassian/bitbucket/__init__.py
atlassian/bitbucket/base.py
atlassian/rest_client.py

[BitBucket] Fix missing function for paged API.

---

examples/jira/jira_issue_update_epic_link.py

Just thought of contributing an example related to multiple issues updating the EPIC link custom-field.
Hopefully its helpful!

[JIRA] : update issues epic link example

---

atlassian/jira.py

This depends on https://github.com/atlassian-api/atlassian-python-api/pull/645
This adds the Jira /createmeta endpoint!

Add "Jira.issue_createmeta()"

---

atlassian/jira.py
examples/jira/jira-issue-type-counter.py

1) Def with list of Issue Types added to Jira.py
2) Script with counter of all issues for every issue type in jira and
percentage of them in certain category

[Jira] Issue types

---

atlassian/bitbucket/__init__.py
atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/bitbucket/cloud/repositories/pipelines.py
atlassian/bitbucket/cloud/repositories/pullRequests.py
atlassian/bitbucket/server/__init__.py
atlassian/bitbucket/server/common/__init__.py
atlassian/bitbucket/server/globalPermissions.py
atlassian/bitbucket/server/projects/repos/__init__.py
atlassian/confluence.py
atlassian/jira.py
docs/bitbucket.rst
examples/bitbucket/bitbucket_branch_restrictions.py
examples/confluence/confluence_copy_labels.py
tests/mockup.py
tests/test_bitbucket_server.py

Scanned over whole repository and fixes some typos.

All: Fixes typos

---

examples/jira/jira_add_label_tag.py

thanks for the discovery of the "black" python formatting tool !

[JIRA] add example jira_add_label_tag.py

---

atlassian/jira.py

Could it be released into pip?

JIRA: add 'update' property to create_issue

---

.github/workflows/test.yml

Split commands to get separate logs in CI.

[Test] Split build and run of Docker container.

---

atlassian/jira.py

Implementation for REST API https://docs.atlassian.com/software/jira/docs/api/REST/latest/#api/2/version-delete

[Jira] Ability to delete a version

---

examples/confluence/confluence_attach_file.py

The CI failed due to an unused import and variable.

CI build fixed

---

atlassian/bitbucket/__init__.py

Allows to run a quick check for the presence/availability of a Bitbucket project.

[Bitbucket] Check for the project existence

---

atlassian/jira.py

Also fixes this open issue #606

[JIRA] Add a funciton to get issues for board

---

atlassian/jira.py

Bulk issue  field update

---

atlassian/jira.py

Fixing includeArchived param
Adding expand param

Fixing get_all_projects and projects params

---

atlassian/bitbucket/__init__.py

Documents have atlassion instead of atlassion.

Correcting Atlassion to Atlassian

---

atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/bitbucket/cloud/workspaces/__init__.py
atlassian/bitbucket/cloud/workspaces/projects.py
atlassian/bitbucket/server/projects/__init__.py
atlassian/bitbucket/server/projects/repos/__init__.py
tests/test_bitbucket_cloud.py
tests/test_bitbucket_server.py

Add function mentioned in #757. @rodalli Can you check this on your side?
Closes #757.

[BitBucket] Add exists function to clound and server OO interface.

---

atlassian/bitbucket/cloud/base.py
atlassian/bitbucket/cloud/repositories/pipelines.py
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/testrepository1/pipelines/GET

Do internal paging as suggested in #755.
Closes 740

[Bitbucket] Pipeline paging workaround

---

atlassian/bamboo.py
atlassian/bitbucket/cloud/base.py
atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/bitbucket/cloud/repositories/branchRestrictions.py
atlassian/bitbucket/cloud/repositories/issues.py
atlassian/bitbucket/cloud/repositories/pipelines.py
atlassian/bitbucket/cloud/repositories/pullRequests.py
atlassian/bitbucket/cloud/workspaces/__init__.py
atlassian/bitbucket/cloud/workspaces/projects.py
atlassian/bitbucket/server/common/permissions.py
atlassian/bitbucket/server/projects/__init__.py
atlassian/bitbucket/server/projects/repos/__init__.py
atlassian/confluence.py
atlassian/jira.py
atlassian/service_desk.py

@gonchik @Amnesycks mentioned a problem in https://github.com/atlassian-api/atlassian-python-api/pull/762#issuecomment-828324681, this is the fix.

Fix problem mentioned in #762

---

examples/confluence/confluence_trash_cleaner.py

https://github.com/atlassian-api/atlassian-python-api/pull/690 broke the Confluence trash cleaner example

confluence_trash_cleaner.py broken by API change

---

atlassian/bitbucket/__init__.py

[BitBucket] Fix get_changelog

---

atlassian/bitbucket/cloud/repositories/pullRequests.py
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/testrepository1/pullrequests/1/comments/GET
tests/test_bitbucket_cloud.py

[BitBucket] Add function to get comments of PR.

---

atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/bitbucket/cloud/workspaces/__init__.py
atlassian/bitbucket/cloud/workspaces/projects.py
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/TestRepositoryCreated/POST
tests/test_bitbucket_cloud.py

Implement create method mentioned in #760.
Closes #760.

[Bitbucket] Add create method for repository.

---

atlassian/bitbucket/__init__.py

Bug: Fix Git LFS endpoint url

---

atlassian/jira.py

Added params Start, Limit and Expand for get_project_issuekey_all method.

Added params for get_project_issuekey_all

---

atlassian/jira.py

[Jira] Do not filter project keys too aggressively.

---

atlassian/bitbucket/cloud/base.py

Fix paging for APIs with parameters.

---

atlassian/jira.py

Respect `advanced_mode` in calls of jql.

---

atlassian/jira.py

Adds missing parameter argument for projects get request

Added parameters to projects get request

---

atlassian/jira.py

Adds edit filter method for updating existing Jira filters

Edit filter method added

---

atlassian/jira.py

Adds these methods:
* Get Jira filter share permissions
* Add Jira filter share permission
* Delete Jira filter share permission

Methods for Jira filter share permissions

---

atlassian/jira.py
docs/jira.rst

Added issue_restore method, which restores an issue from archive. Updated docs.

Added issue_restore method

---

atlassian/jira.py

simple extension of the same method used for edit_issue to the create_issue method

add notify users flag to create issue

---

atlassian/jira.py

Reverts atlassian-api/atlassian-python-api#912

Revert "add notify users flag to create issue"

---

atlassian/jira.py

Parameter is not used by the function.

Remove unnecessary parameter from function

---

atlassian/jira.py

[Jira] Update jira.py

---

docs/bitbucket.rst

Based on the implementation here: https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket/__init__.py#L2244

Update parameter name to repository_slug

---

atlassian/service_desk.py

Service Desk: Change logging level

---

atlassian/jira.py

[Reference link](https://confluence.atlassian.com/jirakb/how-to-access-upm-rest-api-for-license-details-777021716.html)

Method for getting info about license object

---

atlassian/service_desk.py

See #967, changed "create request" log in #968

Change logging level

---

atlassian/bitbucket/__init__.py

This methods fetches categories assigned to your projects or repositories

add get_categories method

---

atlassian/bamboo.py
docs/bamboo.rst

[Bamboo] Allow searching for plans by name

---

atlassian/jira.py

This PR attempts to align the python API with the Rest API.  ([v2](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-permissions/#api-rest-api-2-mypermissions-get) and [v3](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-permissions/#api-rest-api-3-mypermissions-get) API's for "mypermissions")
[atlassian_black.txt](https://github.com/atlassian-api/atlassian-python-api/files/9223456/atlassian_black.txt)
[atlassian_make-docker-qa.txt](https://github.com/atlassian-api/atlassian-python-api/files/9223458/atlassian_make-docker-qa.txt)
[atlassian_tox.txt](https://github.com/atlassian-api/atlassian-python-api/files/9223459/atlassian_tox.txt)

[Jira] Get Permissions parameter addition for permissions

---

atlassian/bitbucket/__init__.py

to go with the existing ones for projects. Use sets to ensure uniqueness in the resulting lists

add administrator_permissions functions for repos

---

examples/jira/jira_dc_remove_stale_nodes.py

Remove stale nodes from cluster before version 8.10

Remove stale nodes from cluster

---

atlassian/confluence.py

Logging change to address issue #1003

[Confluence] Logging page content as info

---

atlassian/bitbucket/cloud/common/users.py
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/testrepository1/pullrequests/1/GET
tests/test_bitbucket_cloud.py

Added an avatar property to the Bitbucket Cloud user object.

[Bitbucket Cloud] Add avatar property to user object

---

atlassian/confluence.py

Added ?status=current to update api call. This is to resolve issue #797

Confluence: update_page method

---

atlassian/bitbucket/cloud/repositories/commits.py

- Fix each commit obj
- Fix get commit message
- Fix get commit author

Fix bitbucket cloud commits #1071

---

atlassian/rest_client.py

Fix for https://github.com/atlassian-api/atlassian-python-api/issues/1094

Let it buid for RHEL-9 again

---

docs/bitbucket.rst

fixed up the documentation for forking to a new project. The documentation was out of date.

fixed up the documentation for forking to a new project

---

atlassian/jira.py
atlassian/rest_client.py

Added some add an remove commands for custom fields in Jira

Add custom field editing

---

docs/jira.rst

As mentioned in my issue #1054 there were missing method calls for the already existing methods.
- get_issue_chaneglog
I've also added documentation for work log methods
- issue_get_worklog
- issue_worklog
Hope the format is ok. It's my first PR ever :-D

[Jira] Added issue changelog and worklog method calls to docs

---

atlassian/jira.py

Added the `flag_issue` method to provide functionality for flagging and un-flagging one or multiple issues in Jira. This method enhances the versatility of the codebase and allows for better issue management.

feat: Add flag_issue method

---

atlassian/bamboo.py
docs/bamboo.rst

Provide list of deployment results scheduled for execution and waiting in queue.

[Bamboo] Get Bamboo deployment queue

---

atlassian/bitbucket/__init__.py

Make check_inbox_pull_requests to return paged generator

Make check_inbox_pull_requests to return paged generator

---

requirements.txt

Implements https://github.com/atlassian-api/atlassian-python-api/issues/1190

Python: Set requests minimum to 2.31.0.

---

atlassian/bitbucket/cloud/repositories/deploymentEnvironments.py

I was having an issue using this on a large organization and found out there is an issue with this endpoint. After finding the jira issue I was able to build a solution to the problem. This fix has allowed me to run against our large organization.

Bitbucket Cloud: Fixes for repository deployment environments.

---

.github/workflows/test.yml
tox.ini

Update mypy testenv to support python 3.11

Add python 3.11 support to test environment

---

atlassian/confluence.py
atlassian/rest_client.py

Add unauthorized error handling if the response body is not json

add unauthorized error handling

---

atlassian/statuspage.py

Related issue: https://github.com/atlassian-api/atlassian-python-api/issues/1231
Thanks @rschre for feedback.

fix: paths for page_create_template and page_get_templates

---

atlassian/bitbucket/cloud/repositories/pullRequests.py
examples/bitbucket/bitbucket_pr_commits.py
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/testrepository1/pullrequests/1/commits/GET
tests/test_bitbucket_cloud_oo.py

- PullRequest object to contain the Commits 
- Example added 
- Test-case added
Closes Issue #1251

Commit Object addition to Pull Requests - #1251

---

atlassian/jira.py

This commit is provided on behalf of Continental AG and subsidiaries.

[Jira] ArchiveIssue: option to disable email notification

---

.github/workflows/test.yml

enable coverage report

---

atlassian/jira.py

Remove a leftover from commit: https://github.com/atlassian-api/atlassian-python-api/pull/1344/commits/254c2507d257abc4eda84bcdc33ee121d56217be

Remove 'paging_workaround' leftover

---

atlassian/bitbucket/base.py

See https://github.com/atlassian-api/atlassian-python-api/issues/1372

[BitBucket] Fix error with timezone formatting

---

atlassian/confluence.py

Add support for updating/creating Confluence pages using Atlassian Document Format

Add support for Atlassian Document Format (ADF)

---

requirements.txt
setup.py

Fix for https://github.com/atlassian-api/atlassian-python-api/issues/1517

Fix for GH-1517
