atlassian-api/atlassian-python-api

atlassian/confluence.py

The `update_page` method in confluence should not require a `parent_id`.  It looks like the `examples/confluence-update-page.py` also isn't expecting a required parent_id.
I've modified the method to work with a parent_id for old code, and not require it for new code (why I didn't move the named param with default value to the end).
Thanks!
Nick

update_page should not require parent_id

---

atlassian/bamboo.py
setup.py

I needed to query job results, which wasn't supported. Now it's possible to use `job_key` in addition to `project_key` and `plan_key` in the `Bamboo.results()` function.

Bamboo: support getting results for jobs

---

README.rst
atlassian/__init__.py
atlassian/bitbucket.py
examples/bitbucket-changes-between-branches.py
examples/bitbucket-project.py
examples/bitbucket-projects-administrators.py
tests/test_base.py

Since Stash has been renamed to Bitbucket long time ago, it probably makes sense to rename the classes. For backwards compatibility, the 'new' Bitbucket class is also being imported as 'Stash'

Rename stash to bitbucket

---

atlassian/confluence.py

The documentation does not work as `parent_id` cannot be set as null.
This changes the method signature, so I do not know if that is fine with you.
```
status = confluence.create_page(
space='DEMO',
title='This is the title',
body='This is the body. You can use <strong>HTML tags</strong>!')
```
This PR allows for `parent_id` being `None`.
Also `self.get('/rest/api/...` does not allow for server URLs of the format 
```
https://company.atlassian.net/wiki/
```
as the forward slash at the beginning  results here: https://github.com/AstroMatt/atlassian-python-api/blob/81b940d5859cf9dc311fa4e006ded0ea3d8aabe8/atlassian/rest_client.py#L42
to truncate the URL to `https://company.atlassian.net/` and loose the `/wiki`

Add support for parent_id set as Null

---

atlassian/confluence.py

Using `self.get('/rest/api/...` does not allow for server URLs of the format 
```
https://company.atlassian.net/wiki/
```
as the forward slash at the beginning  results here: https://github.com/AstroMatt/atlassian-python-api/blob/81b940d5859cf9dc311fa4e006ded0ea3d8aabe8/atlassian/rest_client.py#L42
to truncate the URL to `https://company.atlassian.net/` and loose the `/wiki`

Remove forward slash as it creates issues for urljoin

---

atlassian/rest_client.py

It was a pain trying to figure out what the error was when I made a mistake. This should fix that. The screenshot is how an error will look now.

Log with log.error to get the errors from Atlassian

---

atlassian/confluence.py

The Confluence REST API now allows access to the body content
convertion functions. Particularly useful when you want to upload wiki
format to Confluence.

Add convert_wiki_to_storage function to Confluence

---

atlassian/confluence.py

If get_pade_id exec with wrong id parameter, don't raise 'AttributeError: 'NoneType' object has no attribute 'get''

Make more comfortable get_page_id behaviour

---

atlassian/confluence.py

I saw the handy method for creating JQL queries in jira.py and decided to give it a try in order to have the same possibility for Confluence. It seems to work well:
`confluence.cql('space=TEST AND created > now("-10y") AND type=page',0,1)`

added CQL method to confluence

---

atlassian/jira.py

* As of limit is by default 50 set in Jira, I removed None value and used 50 as a default argument
* Allowed fields to be passed as a list, in that case it will convert it into comma separated values

Jira.jql() api changes

---

atlassian/confluence.py
atlassian/jira.py

Hi! 
This commit is related to the escaping project parameter
Cheers,

Project method escaping

---

atlassian/rest_client.py

This allows users to pass a custom requests.Session to the rest_client.
This enables things like pre-configuring a session for SSO auth for
servers that do not allow basic HTTP auth.

Add session parameter to rest_client

---

atlassian/rest_client.py

201 is a valid HTTP status code when doing POST method, it means the resource has been created.
So we shouldn't show error log for status 201.
Below is what I encountered in real case:
```
DEBUG:atlassian:Received: 201
<Response [201]>
DEBUG:atlassian:curl --silent -X POST -u '*****':'********' -H 'Content-Type: application/json' -H 'Accept: application/json' --data '"{\"fields\": {\"project\": {\"key\": \"GIS\"}, \"issuetype\": {\"name\": \"Golden Image\"}, \"summary\": \"Test Subject\"}}"' 'https://example.com'
ERROR:atlassian:{u'self': u'https://example.com/rest/api/2/issue/11793', u'id': u'11793', u'key': u'GIS-10'}
```

Support HTTP status code 201 in rest_client

---

atlassian/jira.py

Perhaps, not only it will be useful for me to receive labels.
Of course, you can get them like this:
Jira.issue("Jira-5116")['fields']['labels']
But it is more convenient:
Jira.get_issue_labels("Jira-5116")

Get labels

---

atlassian/jira.py

WIth include_inactive_users you get both active and inactive users. Now you can make a request only for inactive users.

Jira: user_find_by_user_string(). Add "include_active_users" param.

---

atlassian/jira.py
docs/jira.rst

Updated the docs to match as well. 
Unfortunately, I haven't found a way to prevent the printing of the response in create_or_update_remotelinks. I don't know if there's a way to suppress that that I'm just not seeing, or if it's just the way it works, so I hadn't updated it. If you know how to, feel free to add that or let me know how to do it.
I plan on adding the application portion to the create_or_update_issue_remotelinks, but I can only access Jira and Confluence while at work and our Jira is in the process of being upgraded so the Jira to Confluence link is broken at the moment, so I'm unable to test.

Added delete_issue_remotelink_by_link_id

---

atlassian/confluence.py

It will allow to create Confluence pages that will be interpreted
with the wiki markup syntax.
More info about Confluence formats here:
https://confluence.atlassian.com/doc/confluence-markup-283640216.html
Change-Id: I2534634a1b1eec1b9d970e5a055b8e73735fd8c9

Add Confluence markup format parameter

---

atlassian/bamboo.py

This PR should fix an error when you try to use functions, which refer to the "results" function
`Traceback (most recent call last):
File "/Users/dmitrij.djachkov/Code/Bamboo/bamboo_cleaner.py", line 14, in <module>
for result in bamboo.plan_results(project_key='TEST', plan_key='TESTPLAN'):
File "/Users/dmitrij.djachkov/Code/atlas-python/lib/python3.7/site-packages/atlassian/bamboo.py", line 165, in plan_results
label=label, issue_key=issue_key, start_index=start_index, max_results=max_results)
TypeError: results() got an unexpected keyword argument 'label'`

FIX Bamboo.results() function - add missing 'label' parameter

---

atlassian/confluence.py
docs/confluence.rst

create_page already support this, so support is extended to:
* update_page
* update_or_create
* update_existing_page
* append_page

add representation support to all confluence actions modifying content

---

atlassian/rest_client.py

In my Confluence instance I needed to be able to inject different cookies.  This change allows Cookies to be declared during creation of the AtlassianRestAPI object.

Adding ability to pass cookies

---

atlassian/bamboo.py

Fixing `TypeError: base_list_call() missing 1 required positional argument: 'label'`

Bamboo: fix error in base_list_call()

---

atlassian/jira.py
docs/jira.rst

The set_issue_status_by_id method sets the status not by task id, but by the transaction id.

Rename set_issue_status_by_id and update jira.rst

---

atlassian/bitbucket.py

Can't find any 'permission' parameter to implement in documentation.
https://docs.atlassian.com/bitbucket-server/rest/4.5.1/bitbucket-rest.html#idp2397808

Fix undefined name 'permission' in project_remove_user_permissions

---

atlassian/bitbucket.py

Add get_default_branch method for bitbucket api.
Doc refernce:
https://docs.atlassian.com/bitbucket-server/rest/5.6.2/bitbucket-rest.html#idm46036344522432

Implement get_default_branch method in bitbucket resourse

---

atlassian/confluence.py
docs/confluence.rst
tests/test-confluence-attach.py

I implement a new method called attach_content() in the confluence module. This new method is very similar to attach_file(). See #280 for more details.
The overall diff log looks a little bit confusing here in Github, because single steps are combined. Avoid duplicate code attach_file() uses now attach_content()

issue 280: implement the new method confluence.attach_content()

---

atlassian/confluence.py
docs/confluence.rst
tests/test-confluence-attach.py

This pull request addresses issue #281 and extends the method confluence.attach_file(). The parameter are now similar to confluence.attach_content(). The caller can specify the attachment name and the content type. Both parameters are optional and in the default case the old behavior (attachment name is build from the filename and the content type from the file extention) is used.  
Attention this pull request based includes also changes from pull request #283 (issue: #280)!
Test case is available and documentation is updated

Issue 281: extend confluence.attach_file() - attachment name and content type

---

atlassian/bitbucket.py

Add method to retrieve pull request comments by comment_id.
documentation:
https://docs.atlassian.com/bitbucket-server/rest/6.4.1/bitbucket-rest.html#idp281

Add method to get pull request comment by id to bitbucket class

---

atlassian/jira.py

Docs:
https://docs.atlassian.com/DAC/rest/jira/6.1.html#d2e1078
I don't understand why you add 'fields' by default if you don't use them in return.

Add get_issue_transitions_full method to Jira class

---

atlassian/confluence.py

The 'expand' parameter is defined for the API, but until now the code did not support it for this particular function.

Confluence: Add expand parameter to get_all_spaces

---

atlassian/rest_client.py

For every request the requests module guesses the correct encoding, which takes time.
Therefore this commit sets the encoding to uft-8.
From https://2.python-requests.org/en/master/user/quickstart/ 
>>>
Requests will automatically decode content from the server. Most unicode charsets are seamlessly decoded.
When you make a request, Requests makes educated guesses about the encoding of the response based on the HTTP headers. The text encoding guessed by Requests is used when you access r.text. You can find out what encoding Requests is using, and change it, using the r.encoding property:
r.encoding
'utf-8'
r.encoding = 'ISO-8859-1'
If you change the encoding, Requests will use the new value of r.encoding whenever you call r.text. You might want to do this in any situation where you can …

Set response encoding to utf-8

---

atlassian/service_desk.py

`ServiceDesk::create_customer_request()` requires a require_type_id to successfully create a request type. The Service Desk API supports a route for gathering the request types, but is not included in this implementation. I've added that so users can now gather request types for a given service desk.
Lastly, there were some `pylint` cleanups (mostly lines too long) I worked on.

Add request types and minor cleanups

---

docs/confluence.rst

I tested and found that the max number of articles one can get by calling *get_all_pages_from_space* is 100. I think it would be useful to add that to the documentation.

add limit restriction for get_all_pages_from_space

---

atlassian/bitbucket.py
examples/bitbucket-project.py

Fix Bitbucket.project() to match Atlassian REST API for Bitbucket Server. The result is not a paged API and does not contain a 'values' key. Tested against Bitbucket Server version 6.0.1.

Fix Bitbucket.project()

---

docs/confluence.rst

Previously the documentation erroneously indicated that Confluence.update_page() required the parent page id as the first positional argument when it actually is a kwarg. Also add the missing minor_edit kwarg.

Docs: Correct documentation of Confluence.update_page()

---

atlassian/rest_client.py
docs/index.rst
requirements.txt
setup.py

Support for Kerberos authentication (#322). Unfortunately the Windows package differs from the rest of the world.
[requests-kerberos](https://github.com/requests/requests-kerberos) could be a better choice but I was unable to get it working on Windows. Every attempt ended in https://github.com/requests/requests-kerberos/issues/96.
This is still a draft because I couldn't figure out what's wrong with the _tox_ builds yet. Pytest works locally though.

Kerberos authentication support

---

setup.py

To determine the window, check the win32. With the verification that is now, there will be problems in the Mac OS:
```
$ python
Python 3.7.4 (default, Jul  9 2019, 18:15:00)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> sys.platform
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'sys' is not defined
>>> import sys
>>> sys.platform
'darwin'
>>>
$ sw_vers
ProductName:  Mac OS X
ProductVersion:  10.14
BuildVersion:  18A391
```
https://docs.python.org/3/library/sys.html#sys.platform

sys.platform => platform_system

---

atlassian/confluence.py

I came about this while trying to use the api to upload attachments to a page that didn't have any attachments associated to it.
I got a KeyError on this line and changing it to use .get instead of indexing it fixed it for me.

Check if the size exists before actually indexing it DLS

---

atlassian/rest_client.py

The error message on the first import is a little misleading on windows: it appears always, but everything is ok. I'm not sure if is is needed anyway since the import error is a valid case on windows.
For the second message: Does it make sense to throw an error here? At this point it's not possible to continue with a valid state.

Log level of package imports adjusted

---

setup.py

A first attempt to make the _kerberos_ dependency optional (#349).
```sh
> pip install atlassian-python-api
> pip install atlassian-python-api[kerberos]
```

Optional Kerberos dependency

---

.travis.yml

A Python 3.7 CI build and clean-up of the deprecated `sudo` option.

Python 3.7 CI build

---

atlassian/rest_client.py
docs/index.rst
tox.ini

Some open issues mentioned in #353 fixed:
1. Exception if kerberos is used but not installed
1. Tox config updated to include the extra dependency
1. Note added to the documentation. Is this enough or is a full pip call more suitable?

Kerberos follow-up

---

atlassian/confluence.py

Hi there,
**TL;DR:** This patch intends to fix the `remove_page_attachment_keep_version()` method in the `Confluence` class, so that it only removes (some) of the versions and not the attachment as a whole.
**Background:** I am faced with a Confluence instance that has been around for some years and for reasons™ had several hundreds of times the exact same versions of most of its attachments uploaded to it by a third party Confluence plugin, over and over again. In order to free up dozens of gigabytes of disk space, I am trying to use this library to iterate over the pages in a particular space and for each attachment found on these pages to delete all versions of the attachments except the most recent ones. The `remove_page_attachment_keep_version()` method seems to be intend to do just …

fixing Confluence.remove_page_attachment_keep_version() method

---

atlassian/bitbucket.py

Hi,
according to this page
https://metacpan.org/pod/WebService::BitbucketServer::Core::V1#get_tags
the name of the parameter for the filtering is filterText.

fix/change the parameter filter of get_tags to be filterText

---

atlassian/rest_client.py

Whenever the HTTP response is with error code 400, some info is logged.
But there are two variables for only one {}. That makes the format function fail.

Fix format error in log 400 code error

---

atlassian/jira.py
atlassian/rest_client.py

The REST API `rest/api/2/user/application` was not implemented.
The PR aims at adding it.
It also add an utility function to easily determine whether the user already has a specified application role.

Add 2 application related functions for Jira

---

atlassian/confluence.py

Add Ability to expand status for membership list

---

atlassian/confluence.py

Attention: If anyone use parameter start and limit to call Confluence.get_page_by_title() he will get an TypeError exception

Issue 286: Confluence.get_page_by_title() works like Confluence.get_page_by_id()

---

atlassian/bitbucket.py
docs/bitbucket.rst
examples/bitbucket-branch-restrictions.py
examples/bitbucket-manage-pull-request.py

New methods added:
- Set branches permissions
- Delete single branch permission by permission id
- Get single branch permission by permission id
- Decline pull request
- Check if pull request can be merged
- Merge pull request
- Reopen pull request

Bitbucket: new methods

---

atlassian/confluence.py

Confluence: Referencing none-existing pages will return None instead of throwing a runtime error

Confluence: Referencing none-existing pages will return None

---

atlassian/confluence.py

Using get_all_pages_by_label returned a 400 when the label included dashes (e.g. test-label-with-dashes).
Wrapped the label in quotes when building the cql query.

Wrap label in quotes to handle labels with dashes.

---

atlassian/confluence.py

I hit this issue, https://github.com/atlassian-api/atlassian-python-api/issues/317 as well when I was trying to update just the title of a confluence page. The current method in determining if an update only considers the body content of the confluence page.
Include the title in comparing page content.
Updating confluence pages.

Include title in determining if there is a difference

---

atlassian/service_desk.py

Hi. Few methods in `ServiceDesk` api falls if `advanced_mode` is `True`, because they expecting data and not `Request` obj.

Fix few get requests in ServiceDesk API falls if advanced_mode is on

---

atlassian/bitbucket.py
atlassian/rest_client.py

My idea for https://github.com/atlassian-api/atlassian-python-api/issues/232
It will only contains the base part, so it will not break anything.  ( I hope)
The API 2.0 endpoints must be added, because I can't test it without an cloud account.

Prepare for Bitbucket API 2.0

---

atlassian/confluence.py

This is a quick fix for an issue. I think we should make a review of the advanced_mode features for all methods. 
It not the first time, when some troubles appear because of that.

Confluence: fix #412

---

atlassian/jira.py

Adding support to update rank of issues through the API documented at https://docs.atlassian.com/jira-software/REST/7.0.4/#agile/1.0/issue-rankIssues

Added support for updating rank

---

atlassian/bamboo.py
docs/bamboo.rst

I used this method to batch-disable several Bamboo branches I didn't want running anymore.
The relevant docs on the Atlassian side are at https://docs.atlassian.com/atlassian-bamboo/REST/6.10.4/#d2e4780, which shows the `/plan/{projectKey}-{buildKey}/enable` URL supports both POST to enable a plan and DELETE to disable a plan.
Opportunistic cleanup: the title of the Bamboo docs incorrectly said it was Confluence.

[Bamboo] Add disable_plan method

---

atlassian/confluence.py

This is a fix for a bug that makes the Confluence library think that every page needs to be updated.
The 'title' key does not exist in the dictionary returned by get_page_by_id() with expand set to 'body.storage', so current_title in the title comparison always evaluates to None.
I moved the title check before the body check and removed the expanded option from get_page_by_id so we can access the correct title value.
Tested against Confluence 6.13.8

[Confluence] Fix page title comparison

---

atlassian/rest_client.py

I just simply added `proxies` parameter for initialization of AtlassianRestAPI class. 
this parameter will be used on sending request.
So that we can use this awesome library even in proxy environment.

support proxy connection for rest client

---

atlassian/jira.py

Added parameter for user() method:
- get user by key
Now you need to use only named parameters.
For example, user(username='john') or user(key='john.d').
You can use only one parameter: username or key.

Added parameter for user() method

---

atlassian/utils.py

The current` is_email()` has a faulty check for whether the input argument is an email. It accepts non string arguments but matches the regex only for arguments that are string. For all other argument types ex: integer, the check is returned True. The fix is to cast the argument as `str` and then perform the check

Check for if an element is a valid email

---

atlassian/bitbucket.py
docs/bitbucket.rst

#469 
Add the ability of adding one or multiple reviewers when opening a Pull Request.
[`atlassian.bitbucket.Bitbucket.open_pull_request`](https://github.com/atlassian-api/atlassian-python-api/blob/f2566d85163a2815b2b77f16b44a26510d59605b/atlassian/bitbucket.py#L846)

[Bitbucket] Add reviewers when opening a PR

---

atlassian/utils.py

**Description**
Current `utils.html_table_from_dict()` creates an HTML table with header cells in the top row only. The new `utils.html_table_from_nested_dict()` converts a nested dictionary into an HTML table with header cells in the top row and first column
**Usage**
```
ordering = ['manager', 'admin', 'employee_count']
data = {
'project_A': {'manager': 'John', 'admin': 'admin1@example.com', 'employee_count': '4'},
'project_B': {'manager': 'Jane', 'admin': 'admin2@example.com', 'employee_count': '7'}
}
utils.html_table_from_nested_dict(data, ordering)
```
**Output**
<table><tbody>
<tr><th></th><th>Manager</th><th>Admin</th><th>Employee Count</th></tr>
<tr><th>Project A</th><td>John</td><td><a href="mailto:admin1@example.com">admin1@example.com</a></td><td>4</td></tr>
<tr><th>Project …

[Utils] method to convert a nested dictionary into an HTML table with header row and header column

---

atlassian/bitbucket.py

Added a function to request participants and their statuses. It may be useful if you want to check whether a pull request was approved by any user or by a particular user. 
I tried to match code style around :)

Bitbucket. Added function to request PR participants

---

atlassian/bitbucket.py
atlassian/rest_client.py
docs/bitbucket.rst

- originated from #475
- implementation of several Pipelines-related REST APIs
- tested with a small [test repo](https://bitbucket.org/pylipp/test-rest-api-wrapper/addon/pipelines/home#!/) of mine
Side note: I'm used to work with URLs like `https://api.bitbucket.org/2.0/user/repo/pipelines/`, hence I used the `resource_url()` method to construct URLs (I set up a Bitbucket instance as `bb = Bitbucket("https://api.bitbucket.org", api_version="2.0", api_root="")`. I'd find it beneficial if more methods of the `Bitbucket` class used this approach instead of having the `rest/api/` path hardcoded. I'd provide a separate PR if you don't see any objections.

Wrappers for Bitbucket Pipelines REST API

---

atlassian/confluence.py
atlassian/errors.py
atlassian/rest_client.py

This is a suggestion for implementing better error handling as noted in #257.
**Overview**
* rest_client.AtlassianRestAPI.request: Propagate errors from requests by using the `raise_for_status` method in the response object.
* errors: Define custom exception classes.
* confluence: Use exception chaining to raise the custom exceptions to convey more useful information when possible.
**Notes**
* The improved error handling is implemented for Confluence only right now. This is the Atlassian product I use (and can thus test) most right now. It also appears to have a smaller API surface than Jira for instance.
* I wasn't completely sure about the coding style, but attempted to shorten the exception messages to a reasonable length.
* The names of the custom exception classes could probably be …

Improve error handling

---

atlassian/jira.py
docs/jira.rst

As described in  #495 this adds support for transitions with mandatory fields.
The default behavior of `set_issue_status` is not changed as the new parameter `fields` defaults to None

Add fields to issue transitions

---

atlassian/bitbucket.py
atlassian/rest_client.py

This PR updates some methods for accessing the Bitbucket Cloud pullrequest API.
It also contains a fix for simpler debugging using curl.

Update for Bitbucket Cloud 2.0 Api

---

atlassian/jira.py
docs/jira.rst
examples/jira/jira-sprint-create.py

- Added the `create_sprint` functionality within jira
- Placed docs for it in docs/jira.rst - added separate section for **Manage Boards**
- Added example at jira-sprint-create.py
Closes Issue #506

[JIRA] Create Sprint

---

examples/confluence/confluence-export-pages.py

I think the id key needs to be in quotes in this example. Here's a PR for it.

id in quotes

---

atlassian/confluence.py
atlassian/errors.py
examples/confluence/confluence-nested-error.py

Provide a new propety ApiError.reason to access the reason for an API error. Also provide an example file to show how to use it.
Note that it had not been fully tested under Python 2.
This closes #513 
Signed-off-by: Daven DU <davendu@tencent.com>

feat: nested error for Confluence

---

atlassian/jira.py
docs/jira.rst
examples/jira/jira-add-issues-to-sprint.py

* Added the `add_issues_to_sprint` functionality within jira
* Placed relevant docs in docs/jira.rst
* Added example at jira-add-issues-to-sprint.py
Added an example also for `jira.create_issue` as it seemed helpful for me and can be for others too.
Closes #486

[JIRA] Issues Add/Move to Sprint

---

atlassian/confluence.py

So, I copied other methods, and cribbed directly from the API example (https://developer.atlassian.com/cloud/confluence/rest/api-group-experimental/#api-api-space-spacekey-permission-post) to get this to work.
Caveat - There's no error handling, so if, for example, the permission already exists for space, you get an ugly (and uninformative):
> 400 Client Error: Bad Request for url
I was just happy I got it to work at all. :-}

Confluence add_space_permission method

---

README.rst
atlassian/confluence.py
atlassian/rest_client.py

I think this is a useful change, especially if Atlassian ever gets around to implementing https://jira.atlassian.com/browse/CLOUD-6999.
However the Documentation link in README.rst is showing version 1.15.3 (https://atlassian-python-api.readthedocs.io/) which doesn't include the section "To authenticate to the Atlassian Cloud APIs".
Can that be updated? It would probably be better if that was done before accepting this PR.
Thanks!

Setting api_version=cloud when Cloud=true

---

atlassian/jira.py
examples/jira/jira-notification_schemes_duplicates.py

Add to methods. One for find all notification schemes and second for get all information about single scheme.

Add methods for notification schemes

---

atlassian/confluence.py

Page_id becomes useless when you implement article transfer between multiple web services.

Add get_parent_content_title func

---

atlassian/confluence.py

find a list of child id
find a list of child title

Find a list of Child id/title

---

atlassian/bamboo.py

Make start_index and max_results args as keyword arguments.

BugFix: positional args start_index and max_results misplased in plans()

---

docs/index.rst

The docs currently say to use the "cookie" parameter for cookie authentication, but the code actually uses the "cookies" parameter (plural).
See https://github.com/atlassian-api/atlassian-python-api/blob/23370dd1cbf7b1999131412096d5e1b4908098b8/atlassian/rest_client.py#L23-L25

Fix cookie auth parameter in docs

---

CONTRIBUTING.rst
README.rst
atlassian/__init__.py
atlassian/xray.py
docs/index.rst
docs/xray.rst
tests/test_base.py

Add support for v1.0 of the Xray REST api for Server and Data-Center. 
Xray is a Jira plugin which provides Test Management support. I use the REST api for test automation (+feedback) from CI.
NOTE:
* As of now, v2.0 does not cover all functionality provided in the initial version, mainly related to test automation (eg. import of test executions).
* The REST api of Xray for Jira Cloud differs from Jira Server/DC.

feat: add xray rest api (server/data-center) support

---

atlassian/service_desk.py

Fixes: #557 
More like a hotfix...
https://docs.atlassian.com/jira-servicedesk/REST/3.6.2/#servicedeskapi/servicedesk/{serviceDeskId}/attachTemporaryFile-attachTemporaryFile
`This resource expects a multipart post`. 
The experimental headers are however set to `application/json`.

Set correct header for attach_temporary_file for ServiceDesk

---

atlassian/confluence.py
docs/confluence.rst

Add inline task setting checkbox method

Add inline task setting checkbox method

---

atlassian/jira.py

Include the required formatting for the parameter `started`.
Resolves #579

[JIRA] Update jira.issue_worklog() docstring

---

atlassian/bitbucket.py
atlassian/confluence.py
atlassian/rest_client.py

Add `__init__` to Confluence and move specific code from `rest_client.py` to this new function.
Change order in `__init__` of Bitbucket to prevent errors if `__init__`of `AtlassianRestAPI` is dependent from the `cloud` flag.

[RestClient] Cleanup base class and fix init order in derived class

---

atlassian/bitbucket.py

When pulling PRs from bitbucket server, the limit url parameter doesn't
seem to be beeing heeded. This change allows the library to prevent too
many PRs from being returned to the client.
In my particular version of bitbucket: Atlassian Bitbucket v5.14.1 
When calling this function I was getting back, even when called with a limit explicitly set. This change allows the client to help the server in the event the server returns more data than we want.

[Bitbucket] Enforce PR limit when using server

---

CONTRIBUTING.rst
README.rst

- Addition of Discord Badge which will redirect to chat group where users can discuss any existing features or required fixes and so on.
- Badge shows number of users online in chat room
- Contributing guidelines added chat group reference
Closes #587

[Feature] Discord Badge Addition

---

atlassian/xray.py
docs/xray.rst

This commit adds the missing pagination support to `get_tests_with_test_set()`
and `get_tests_with_test_execution()`. In addition, it will provide
to option to retrieve detailed Test execution details.

Xray: add pagination support for api methods

---

atlassian/jira.py

Adding get_workflows_paginated as get_all_workflows calls a deprecated API (see https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-workflows/#api-rest-api-2-workflow-get)

Added get_workflows_paginated method.

---

atlassian/bitbucket.py
atlassian/rest_client.py

- Refactor API endpoints to reuse the common leading parts.
- Refactor get call for paging:
- Move code for paging to a separate function and reuse it in the paged endpoints.
- In advanced mode the raw data is returned,
- If limit is given the next page is read until the given limit.
- If limit is None the whole list is retrieved.
The functions are a reordered according to the endpoint url.

[BitBucket]: Refactor url handling.

---

atlassian/bitbucket.py
atlassian/rest_client.py
examples/bitbucket/bitbucket-branch-restrictions.py
examples/bitbucket/bitbucket-changes-between-branches.py
examples/bitbucket/bitbucket-clean-jira-branches.py
examples/bitbucket/bitbucket-fork-repository.py
examples/bitbucket/bitbucket-tag-manipulations.py

This PR fixes a bunch of issues/regressions introduced in the BB Cloud client with #609.
**Note:** It seems like a lot of refactoring was done without a proper Python IDE? Something like [PyCharm](https://www.jetbrains.com/pycharm/) + [Mypy](https://plugins.jetbrains.com/plugin/11086-mypy) + [Pylint](https://plugins.jetbrains.com/plugin/11084-pylint) + [SonarLint](https://plugins.jetbrains.com/plugin/7973-sonarlint) would easily have alerted the developer of.
The PR also adds support for the alternative Bitbucket Cloud API URL, i.e. `https://api.bitbucket.org/2.0` instead of `https://bitbucket.org/api/2.0`.

Fix broken Bitbucket Cloud client

---

atlassian/constants.py
atlassian/jira.py
docs/jira.rst
examples/jira/jira-issues-csv-export.py

To provide option to export CURRENT fields also in addition to existing ALL fields
Default : ALL fields (existing and non-breaking change)
- Functionality addition in `atlassian/jira`
- Example added
- Constants file added to have project related constants
- Docs example added
Closes #602

[JIRA] Issues export to CSV +current fields option

---

atlassian/bitbucket/__init__.py

The commit a9c6159bcf98992a4bb892a2fb4ad8090c3bd836 changed the URL handling. The non default API roots are changed wrong. 
I've searched in the old implementation all endpoint not matching the default root `rest/api` with the regular expression `['"]\/?rest\/(?!api)` and checked the new implementation.
I think that the old implementation of `get_project_condition` used the wrong endpoint. According to the [documentation](https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-default-reviewers-rest.html#idm52264901504) the endpoint for a specific condition is `/rest/default-reviewers/1.0/projects/{projectKey}/condition/{id}` and not `.../conditions/{id}`.
closes #619

[Bitbucket] Fix wrong URLs after refactoring

---

atlassian/confluence.py

get_page_child_by_type should return whole response from Confluence, to be able to properly use pagination.

[Confluence] Return full response in Confluence.get_page_child_by_type

---

.github/bump_version
.github/workflows/test.yml
CONTRIBUTING.rst
README.rst
docs/index.rst
pyproject.toml

- Update documentation.
- Switch status badge to GitHub.
- Call bump_version in GitHub actions.

[Tests] Remove/Replace references to Travis CI.

---

atlassian/service_desk.py
docs/service_desk.rst

This covers #454 due to the deprecation noted [here](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/).

Update adding and removing users to organization

---

atlassian/jira.py

This depends on https://github.com/atlassian-api/atlassian-python-api/pull/645
Sometimes it is useful to add "renderedFields" as expand keyword when retrieving fields or issues. This adds the "expand" keyword to the respective Jira methods :)

add "expand" Jira.issue and Jira.issue_field_value

---

atlassian/rest_client.py

Disclaimer: I only looked at Jira until now :)
Currently there seems not to be a method which adds multiple GET parameters to the API request. Indeed, these might happen in the future (I will add another Pull Request  to add the "expand" keyword to Jira.issue_field_value() and Jira.issue() ;) )
This Pull Request adds the option to have multiple GET parameters in the URL.

Add URL encoding for multiple GET parameters

---

atlassian/bitbucket/__init__.py
docs/bitbucket.rst

The Update Repo command is missing from the Bitbucket API allowing for updates to repository eg description. 
The method arguments follow the same pattern used by the `update_project` method.
The change covers both code and docs, and all tox checks pass.

Bitbucket: Feature/Update Repo command

---

atlassian/service_desk.py

Sorry, I missed a commit to fix for #649 to fix accountIds to be the format per the documentation. Currently, its passing the data as accountIDs which results in a 400.

Fix accountIDs to accountIds to match endpoint

---

examples/bitbucket/bitbucket_cloud_oo.py

In encountered an error in the bitbucket cloud example. This PR fixes it. It replaces the parameter for the workspace request. The example tried to get the workspaces by the workspace name. According to the [documentation](https://developer.atlassian.com/bitbucket/api/2/reference/resource/workspaces/%7Bworkspace%7D) they must be requested by the workspace slug:
> This can either be the workspace ID (slug) or the workspace UUID surrounded by curly-braces
Workspace name and slug are often the same, but in case they are different, the example fails:
`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.bitbucket.org/2.0/workspaces/...`

Bitbucket: Fix error in bitbucket cloud example

---

atlassian/bitbucket/server/base.py
examples/jira/jira_issue_update_epic_link.py
pyproject.toml
requirements-dev.txt
setup.cfg
tests/mockup.py
tests/test_bitbucket_cloud.py
tests/test_bitbucket_server.py
tests/test_servicedesk.py
tox.ini

Flake9 can cause troubles without a virtualenv if working on different projects. Therefore switching back to flake8 and using `setup.cfg`instead of `pyproject.toml`.

[Tests] Replace flake9 with flake8.

---

atlassian/bitbucket/base.py
atlassian/bitbucket/cloud/base.py
atlassian/bitbucket/cloud/repositories/branchRestrictions.py
atlassian/bitbucket/cloud/repositories/defaultReviewers.py
atlassian/bitbucket/cloud/repositories/issues.py
atlassian/bitbucket/cloud/workspaces/projects.py
atlassian/bitbucket/server/base.py
atlassian/bitbucket/server/common/__init__.py
atlassian/bitbucket/server/globalPermissions.py
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/testrepository1/pipelines/{PipelineUuid}/GET
tests/responses/bitbucket/cloud/2.0/workspaces/GET
tests/responses/bitbucket/server/rest/api/1.0/projects/PRJ/repos/GET
tests/test_bitbucket_cloud.py

Fix assertion error from #652. The size value is the overall size and not the size of the current response. Therefore the assertion in the pagination is removed.

[Bitbucket] Fix AssertionError error in pagination.

---

atlassian/service_desk.py

The _requestType_ API endpoint has a _createRequestType_ method that can be used to create new request types.
Documentation here:
https://docs.atlassian.com/jira-servicedesk/REST/4.13.1/#servicedeskapi/servicedesk/{serviceDeskId}/requesttype-createRequestType
I've added some code to implement this method.

[ServiceDesk] Added the "Create request type" method available on the REST API "requestType" endpoint

---

README.rst

In the readme file the link from the badge to the documentation was broken. This fix corrects the link and redirects to the correct page. Got the correct link from: https://readthedocs.org/projects/atlassian-python-api/

Docs: Fix broken documentation link in badge

---

docs/conf.py

I tried to generate the documentation but it failed due to missing theme 'alibaster'. I assume 'alabaster' was meant. 
The documentation theme has been adapted several times. Last time it was reverted to 'alibaster' instead of 'alabaster' (https://github.com/atlassian-api/atlassian-python-api/commit/0b36c5f0079f1179332c63fe82f4c44c52f01fd3#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3).
I changed it to the correct theme.

Docs: Fix typo in documentation theme

---

docs/index.rst

I changed the chapter for the cloud authentication in the documentation. They were outdated and had some errors. Also added some hints.
* Created additional section for Bitbucket cloud authentication, because it differs from the other services.
* Updated to new Cloud class, because others are marked deprecated.
* Gave more information how you can provide your credentials.
* Add information you cannot login with regular password for Jira etc.
* Corrected cloud link

Bitbucket: Corrected documentation for cloud authentication

---

README.rst

Readme file contained several inline code sequences. They were marked with ``. They have no text role, so they are not formatted as code on GitHub. Text role :code: is now used to format the inline code. It better highlights the code sections. [Text roles](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/InlineCode.html)

Docs: Code prefixes for better formatting

---

atlassian/rest_client.py
docs/index.rst
examples/bitbucket/bitbucket_oauth2.py

The current implementation only supports authentication with OAuth 1.0. They are mostly used by the server variants. The cloud services now use OAuth 2.0.
With this commit OAuth 2.0 is now supported without breaking the support for OAuth 1.0. I also extended the documentation and created an example. The example shows a server based on Flask. It does the handshake with Bitbucket and receives the tokens. I also deployed once and tested it successfully.
This can be helpful for some web apps that need to interact with Atlassian services.

Auth: Add OAuth 2.0 authentication support

---

atlassian/bitbucket/cloud/repositories/pullRequests.py
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/testrepository1/pullrequests/POST
tests/test_bitbucket_cloud.py

According to #662 . This adds support for creating a new pull request.

[Bitbucket Cloud] Create pull request support

---

.readthedocs.yml

Documentation builds on read the docs are currently failing. The documentation build is trying to install all required pip packages for development. It fails for one C-package that needs compilation.
The documentation build does not need all these packages. The configuration can be changed in the admin panel of read the docs or with a configuration file. A configuration file is the recommended way.
This commit introduces a basic configuration file for the read the docs documentation build.

Docs: Add configuration file for read the docs

---

.github/workflows/test.yml
Dockerfile.qa
Makefile
atlassian-python-api.code-workspace
atlassian/bitbucket/base.py
requirements-dev.txt
tox.ini

There was a problem with the different python versions. Effectivly only version 3.8.5, which is the default in the docker ubuntu, was used. Now 3.6, 3.7, 3.8 and 3.9 are used.
At the moment the result is only visible inside the log of tox. To make the result vissible in the PR a project in Codecov is needed and the token must be added to this project to be able to upload the data from the GitHub action. We should also define from which python version the result is uploaded.
You can see in https://github.com/gcovr/gcovr/pull/445 how it can look like.
Should we install all python versions inside the docker container and run tox with all python versions?
Closes #657

Add coverage report.

---

docs/conf.py

The version of the documentation is configured in the `conf.py` file. The version has not been increased there for a longer time. On Read the Docs you can find the version information for the library in the title for example. So it looks like the documentation refers to an older version of the library.
The current version of the library is in the `atlassian/VERSION` file. In oder to keep the process simple, I changed the `conf.py` so that the documentation now also takes the version information from the `VERSION` file. By that the version information of the library and the documentation is always in sync.
I set both `release` and `version` to the same value. I think there is no distinction needed for this project.
I tested it locally and it worked well.
[Background …

Docs: Get documentation version from VERSION file

---

tox.ini

When documentation has been built and quality check is run afterwards, it always fails because of errors in the docs/_build/ folder. This is because doc8 is also scanning the generated documentation files for errors.
This commit is adding an ignore-parameter to the call to doc8. With this the build folder is ignored.

Docs: Ignore build folder in doc8

---

README.rst

I was a bit confused that there are two sections about contributing in the readme. I think they could be merged. I removed the upper one and merged it to the lower one. Most of the time the people first want to have installation and usage information and later the contribution info.

Docs: Remove redundant contribution information

---

atlassian/confluence.py

The `create_page` method exposes a way to create new pages with the v2 editor. This PR modifies the `update_or_create` method to expose this same functionality in case the page needs to be created and not updated.
It's a tiny change but I tested it nonetheless and it works fine.

Confluence: add editor parameter to update_or_create

---

docs/index.rst

Documentation gave information about authentication with key and certificate. I could not find this authentication method in the code and as well not in the Atlassian documentation.
Therefore, I removed the chapter is removed and the other authentication methods are grouped with a new title. Maybe you have more information what could be meant there?

Docs: Remove Key-Cert authentication info

---

atlassian/rest_client.py
tests/test_confluence_advanced_mode.py

Added boolean "advanced_mode" switch to post, put and delete methods of RestClient, to make them align with the "[get](https://github.com/atlassian-api/atlassian-python-api/blob/93a47b116ff7fdf4bd092f3780f9dff05d1ff67b/atlassian/rest_client.py#L250)" implementation. This allows the caller to retrieve raw response for individual calls rather than change the property of the RestClient instance.
Added tests that mimic Confluence module behavior and check the type of response.
Closes atlassian-api/atlassian-python-api#681

[RestClient] Added advanced_mode to POST, PUT, DELETE

---

atlassian/bitbucket/cloud/__init__.py
docs/index.rst
examples/bitbucket/bitbucket_cloud_oo.py
examples/bitbucket/bitbucket_oauth2.py

Unlike the server variants, the url for the Bitbucket cloud is always the same. There is no need to write the url every time, when the Cloud class should be used. Also for new users of this library it can be confusing, where to find the Bitbucket cloud url.
Therefore, this commit sets for the url parameter of the Bitbucket Cloud class to a default value. It still can be modified by giving another url as parameter (i.e. for tests). Also adapted documentation and examples.

Bitbucket Cloud: Set default url

---

atlassian/confluence.py

Changed return of get_all_spaces to be able to paginate if you have more than 500 spaces and use start and limit params

[Confluence] get_all_spaces extend parameters

---

atlassian/service_desk.py

with the default 'application/json' content-type the upload is not working
in the documentation there is a hint which headers should be set
if the X-Atlassian-Token is missing you receive a 404

[Jira Service management] Update service_desk.py

---

.github/workflows/test.yml
requirements-dev.txt
tox.ini

@gonchik For public repositories no token is needed. Th codecov.io can be marked as needed request. It fails if the converage decrease.

[Test] Upload coverage data to codecov.io.

---

atlassian/rest_client.py
docs/index.rst
requirements.txt
setup.py

The package currently used on windows is broken on Python 3.9 (PR pending, but the project isn't very active). This PR replaces both kerberos packages with [`requests-kerberos`](https://github.com/requests/requests-kerberos), allowing some improvements:
- Single package, no difference for windows
- API is closer to *oauth*, using a map (the parameter isn't used yet)
- Less code
- Python 3.9 compatibility
It requires external installation of a additional executables on Windows.

[REST Client] Kerberos authentication improvements

---

atlassian/confluence.py

X-Atlassian-Token should be set to “no-check” instead of “nocheck”.
See https://developer.atlassian.com/server/confluence/form-token-handling/
Otherwise the following warning appears in the server log:
[common.security.jersey.XsrfResourceFilter] hasDeprecatedHeaderValue Use of the 'nocheck' value for X-Atlassian-Token has been deprecated since rest 3.0.0. Please use a value of 'no-check' instead.
Also see issue #696

Correct value for "X-Atlassian-Token" field in HTTP header - confluence.py (attach_content)

---

atlassian/bitbucket/cloud/repositories/pullRequests.py

Remove function annotation since this syntax is not supported in Python 2.7
Fix for #704

[Bitbucket] Fix Python 2.7 incompatibility

---

atlassian/bitbucket/__init__.py

Allows to run a quick check for the presence/availability of a repository in the Bitbucket project.

[Bitbucket] Check for the repository existence

---

atlassian/bamboo.py
docs/bamboo.rst

Add agents API based on https://docs.atlassian.com/atlassian-bamboo/REST/7.2.2/. Tested on our Bamboo-7.2.2
#699

Bamboo: Add support for agents API

---

atlassian/bamboo.py

We are still running the atlassian-python-api package on Python 3.4, due to < reasons/enterprise world>.
When I check, this package should be supported even with Python 2.7, therefore, f-string shouldn't be used.
Ref https://github.com/atlassian-api/atlassian-python-api/blob/master/setup.py#L45
I removed the f-string only from package sources themselves. 
I didn't touch tests nor examples.
Fixes: #722.
Signed-off-by: Martin Styk <mart.styk@gmail.com>

Use format instead of f-strings

---

atlassian/bamboo.py
atlassian/jira.py

We have a specific requirement in our work area, where for some issue status changes, we are required to mandatorily provide comments. The current implementation of set_issue_status method doesn't support updating comments, as comments can't be updated via 'fields' and instead should be updated via the 'update' json structure as per the latest Jira Rest API. Instead of creating a bug/enhancement request I thought I can fix it as it is a simple fix. I have tested this fix and it works fine.

Enhanced set_issue_status method in jira module, adding update param

---

docs/jira.rst

Adds documentation for the following Jira methods:
- Jira.get_issue_link()
- Jira.create_issue_link()
- Jira.remote_issue_link()
These methods already exist, they are just currently undocumented. It also renames the titles for the currently-documented remote link methods to indicate they are only for handling remote links (e.g. links external to Jira).
Fixes #724.

[JIRA] Document issue linking methods

---

atlassian/jira.py

The `Jira.get_plugins_info()` method is currently broken. Calling this method results in a 404 client error:
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://platformsh.atlassian.net/rest/plugins/1.0
```
The issue is the URL should have a trailing slash but we don't set `trailing=True` when calling the `Jira.get()` method in the return. This remedies that situation and fixes #703.

[JIRA] Fix get_plugins_info method request in need of trailing slash

---

atlassian/confluence.py

- update_page(always_update=False) allows the content check to be overridded
- get_space(params=None) allows params to be passed, e.g. type and status

Add Confluence update_page(always_update) and get_space(params) methods

---

atlassian/jira.py

There exists a private `project-templates` API endpoint for creating a new project based on an existing project: `rest/project-templates/1.0/createshared`. This PR adds support for this using a new `Jira.create_project_from_shared_template()` method.
This private interface has been described in the following discussions from which I derived this: [[1](https://community.atlassian.com/t5/Jira-questions/rest-api-use-existing-projects-configuration-when-creating-a-new/qaq-p/269708)], [[2](https://community.atlassian.com/t5/Answers-Developer-Questions/Create-new-Project-via-REST-based-on-existing-Project/qaq-p/527104)], [[3](https://community.atlassian.com/t5/Jira-questions/How-to-create-project-with-shared-Configuration-via-REST-API/qaq-p/650062
)], …

[JIRA] Support private endpoint for creating new projects based on a template project

---

atlassian/jira.py
docs/jira.rst

The GDPR changes to the REST API have removed the username parameter from the user search endpoint and now requires either a query, accountId or property parameter be specified otherwise the request will fail. According to the API documentation, a query and accountId cannot both be provided otherwise the request will fail.
This PR brings the Python Jira.user_find_by_user_string() method into alignment with the REST API's post-GDPR changes. It also updates the associated documentation per the contribution guidelines. I tested the functionality against Jira Cloud that my company uses and it worked as expected.
Fixes #726. See that issue for more details. This method is broken until this PR is merged.

[JIRA] User search required parameters additions

---

atlassian/bamboo.py

This method should not use GET, but POST. Otherwise, this functionality will not work as intended. Resulting in 500 returned from Bamboo.
Tested on Bamboo 7.2.2
```
>>> Bamboo(url="https://example.com", username="user", password="pass", advanced_mode=True)
<atlassian.bamboo.Bamboo object at 0x1079c8160>
>>> bamboo = _
>>> bamboo.stop_build("FOO-BAR")
<Response [200]>
```
This should fix the discussion about it here https://github.com/atlassian-api/atlassian-python-api/commit/1a101ee011068a8b40efaad21013faca18c346eb.
Signed-off-by: Martin Styk <mstyk@netsuite.com>

[Bamboo] Fix broken stop build method

---

atlassian/confluence.py
docs/confluence.rst

Confluence template API transitioned to a stable version. Some things in our module are no longer in line with reality. The endpoint URL has changed to `wiki/rest/api/template` and some parameters have changed behavior. When getting templates or blueprints, a space is not required. If it's not given, all templates in the scope will be returned. I updated the parameters to not be required. The limit has also been updated to a default of 25. I switched those limit parameters to have a default "None" type, so if they're not specified, we don't pass them and we'll get the default API behavior.
We don't currently support deleting templates or creating/updating new content templates but there are REST API methods for that, so now is a good time to write that support.
Fixes #715

[Confluence] Update template methods as they are no longer experimental

---

atlassian/xray.py
docs/xray.rst

In my project I've missed the option to update test executions of a test plan. The XRay/Raven REST-API supports it, but the python library didn't had the functions implemented, so I've just implemented them. 😄 
https://docs.getxray.app/display/XRAY/Test+Plans+-+REST
- **get_test_executions_with_test_plan** ->  GET /rest/raven/1.0/api/testplan/{testPlanKey}/testexecution
- **update_test_plan_test_executions** ->  POST /rest/raven/1.0/api/testplan/{testPlanKey}/testexecution
- **delete_test_execution_from_test_plan** ->  DELETE /rest/raven/1.0/api/testplan/{testPlanKey}/testexecution/{testExecKey}
In my project this is working fine. In the tests I couldn't find any tests for xray, so I did not include any.
This is my first pull request ever, so bear with me and let me know if something is …

[XRAY] Adding functions for test executions in test plan

---

atlassian/bitbucket/cloud/repositories/pipelines.py
docs/bitbucket.rst

Adding filter "page" & "pagelen" on pipeline.each()
This can allow to use workaround on #740 as mention in https://jira.atlassian.com/browse/BCLOUD-13806

[BITBUCKET] Allow users to use filter on pipeline

---

atlassian/jira.py

The `location` parameter of the `create_agile_board` must not be sent
for the Jira Server edition.
This parameter is not supported as per the [REST API documentation](https://docs.atlassian.com/jira-software/REST/8.5.8/#agile/1.0/board-createBoard) and
throws an error if sent anyway.

[JIRA] create_agile_board method adapted for Jira Server

---

atlassian/jira.py

Allows users to set the parameter `validateQuery` for the Search API. This can be useful in situations where a request is made for a list of issue keys, containing a deleted issue. Disabling the validation is unsafe (to be used by clients on their own risk), but will prevent:
```
{"errorMessages":["An issue with key 'DELETED-1' does not exist for field 'key'."],"errors":{}}
```
and returns a list of valid issues instead (w/o the above `DELETED-1`)

[JIRA] add parameter `validateQuery` for search API

---

atlassian/bamboo.py
docs/bamboo.rst

New methods added:
- Get deployment users
- Revoke user from deployment
- Grant user to deployment
- Get deployment groups
- Revoke group from deployment
- Grant group to deployment
- Get environment user
- Revoke user from environment
- Grant user to environment
- Get environment groups
- Revoke group from environment
-  Grant group to environment

Bamboo: add environment and deployment permission

---

atlassian/confluence.py
atlassian/jira.py
atlassian/rest_client.py
atlassian/service_desk.py

When the server returns a 4xx or 5xx status code and provides an
error message, that error message will be the message of the exception raised.

Jira, Confluence: Exceptions contain message provided by server

---

atlassian/bitbucket/__init__.py

The call to get members of a certain group in bitbucket does not work because the string format method is being passed a method instead of the result of the method. This is a fix for that issue.

Fix group_members() not working

---

atlassian/bitbucket/__init__.py

This was tested under Bitbucket v6.10.7 Data Center. 
The REST API documentation indicates that the Cloud version does not have an endpoint for the audit log, hence the methods get_project_audit_log() and get_repo_audit_log() will throw an Exception.

[Bitbucket Server] Add support for getting audit log

---

atlassian/bitbucket/cloud/repositories/defaultReviewers.py
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/testrepository1/default-reviewers/DefaultReviewer1Uuid/DELETE
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/testrepository1/default-reviewers/DefaultReviewer1Uuid/GET
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/testrepository1/default-reviewers/GET
tests/test_bitbucket_cloud.py

As mentioned in #679 the uuid shall be used instead of display_name.

[BitBucket] Fix default reviewer.

---

atlassian/xray.py

Per issue #597, this api call should not have a trailing slash according to Xray documentation.

Removed trailing slash from api call for get_tests

---

atlassian/bitbucket/cloud/repositories/__init__.py
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/TestRepositoryCreated/POST
tests/test_bitbucket_cloud.py

Extend create functionas mentioned in https://github.com/atlassian-api/atlassian-python-api/pull/772#issuecomment-836199368. Instead of using kwargs only the option needed at creation time are added.

[BitBucket] Extend repo create method with is_private and fork_policy.

---

Dockerfile.qa

The Docker tests recently started failing with the following message:
RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.
This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
It seems this is related to the recent update of the Click library to version 8. This library is used by tools such as the black formatter.
As a fix, these environment variables are set in the Docker container. This should not affect tests on the host systems, since the hosts usually already have a Unicode locale set.

Fix docker based tests by setting the unicode local.

---

pyproject.toml

Running *pylint* fails with `AttributeError`s:
```
AttributeError: 'int' object has no attribute 'items'
AttributeError: 'float' object has no attribute 'find'
```
Adding the section as shown in https://github.com/PyCQA/pylint/issues/3181#issuecomment-846129966 fixed the first error.
The second one is caused by floats not being handled correctly (fix but unreleased; https://github.com/PyCQA/pylint/issues/4518).
- Tested with 91ddbe2 (latest master commit)
- **Pylint:** 2.8.3
- **Python:** 3.9.5

Fix Pylint failing with AttributeError

---

atlassian/jira.py
docs/jira.rst

Fixes https://github.com/atlassian-api/atlassian-python-api/issues/515 and addresses the comments left in https://github.com/atlassian-api/atlassian-python-api/pull/728.

Jira: Update assign_issue to match the current API

---

atlassian/bitbucket/__init__.py
docs/bitbucket.rst

New methods added:
- project_default_permissions
- project_grant_default_permissions
- project_remove_default_permissions
- all_repo_hook_settings
- get_repo_hook_settings
- enable_repo_hook_settings
- disable_repo_hook_settings
- all_project_repo_hook_settings
- get_project_repo_hook_settings
- enable_project_repo_hook_settings
- disable_project_repo_hook_settings

Bitbucket: add project default permissions and repository hook settings

---

atlassian/bitbucket/base.py

Fix problem mentioned in #801.

[Bitbucket] Clear trailing slash in paged call of next url.

---

atlassian/bitbucket/__init__.py

The following APIs are implemented.
http://example.com/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/webhooks [GET, POST]
http://example.com/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/webhooks/{webhookId} [GET, PUT, DELETE]
Could you please help review and approve this PR?

Fix #805 Support webhook rest api

---

atlassian/jira.py

In some cases, the http api response's "errorMessages" is empty, like this:
`{'errorMessages': [], 'errors': {'fixVersions': 'data was not an array'}}`
appending the errors to the error message is better.

[JIRA] Optimize error msg

---

atlassian/jira.py
examples/jira/jira_issues_get_all_projects.py

Straightforward documentation and example addition, that's all.

[JIRA] Documentation and example addition for getting all projects

---

pyproject.toml

TOML Kit [ends up creating duplicate table names](https://github.com/sdispater/tomlkit/issues/138) and [TOML Lint](https://www.toml-lint.com/) flags this line as invalid. The TOML Kit failure makes it so `atlassian-python-api` [can't be installed via Poetry](https://github.com/python-poetry/poetry/issues/4278).

Fix TOML parsing error in pyproject.toml

---

atlassian/jira.py
examples/jira/jira_issue_assign.py

- Changes to existing Assign Issue to user code
- Example added
- taken from https://docs.atlassian.com/software/jira/docs/api/REST/8.5.0/#api/2/issue-assign
Resolves #775

Assign Issue Fix

---

atlassian/bitbucket/__init__.py

* Bitbucket: request pull requests containing a commit on the correct URL

[BITBUCKET] fix Bitbucket.get_pull_requests_contain_commit

---

atlassian/bitbucket/__init__.py

@gonchik  Can the usage of f-strings be checked with flake8? I found nothing.
Closes #828

[BitBucket] Replace fstring with format function.

---

atlassian/bitbucket/__init__.py

If tag_name is given a single tag is returned, else a generator for the tags (paged API).
Remove ifs in `set_tag` because the tag_name is mandatory, description is the only optional argument.
Closes #827

[BitBucket] Fix get_project_tags.

---

atlassian/jira.py

Fix for calling Jira's "Get project versions paginated" endpoint: 
now the method sends parameters (eg. orderby, query) as a payload with JSON, but API expects that them as GET parameters. So parameters are ignored by Jira API.

Jira: Fix: "Get project versions paginated" ignores passed parameters

---

atlassian/bamboo.py

This PR is to fix the issue with `start_index` getting reset to 0 before the value is assigned to the `start-index` parameter causing results to always start from the beginning.

Fix issue with start_index reset

---

atlassian/bitbucket/cloud/repositories/pipelines.py

Fixes Issue : https://github.com/atlassian-api/atlassian-python-api/issues/847

[bitbucket pipelines] allow commit arg to be optional when only pattern is passed in pipeline trigger api

---

atlassian/bitbucket/__init__.py

Adding ability to fork a repo to a different project that differs from the original source project, which is what the existing
functionality is limited to.
Within a fair few of my workflows and projects I work with, we need to fork the original project to a personal user repo make changes and create pull requests back. Unfortunately in trying to automate these I'm limited in the ability of using this library to be able to bootstrap the workflow.
This is doing the bare minimum fork without adding in any extra properties like fork syncing etc to add the smallest change first that matches the existing mono-project fork.

[Bitbucket] Adding ability to fork a repo to a different project

---

docs/bitbucket.rst

Fix up the docs to include the functions definitions for forking repositories

[Bitbucket]: Fix up docs for forking repos

---

atlassian/bitbucket/__init__.py

Two concurrent if statements that check the same thing, instead of double checking the code, just nesting both statements within the same identical conditional

[Bitbucket] Removing redundant double check for simpler code to read (minor/readability)

---

atlassian/confluence.py

The editor= parameter of the confluence.create_page API will accept 'v1' as well as 'v2' by this change.
The editor='v1' works both in confluence.create_page() and confluence.update_or_create() APIs.
Background:
- The 'v1' parameter is required to make a copy of the existing Confluence page which expects old (v1) editor
to maintain the appearance of the page.

change: allow editor=v1 as a parameter of the create_page function

---

atlassian/rest_client.py
docs/index.rst

Jira Server v8.14 introduces authentication through a [Personnal access token](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html), which is different from the existing cloud authentication.
It works through a simple "Authorization: Bearer <token>" header.
This PR add support for this authentication mechanism.
Tested on Jira server v8.14.1

Jira: Add support for authentication through access token

---

atlassian/bitbucket/cloud/repositories/pullRequests.py
tests/responses/bitbucket/cloud/2.0/repositories/TestWorkspace1/testrepository1/pullrequests/25/GET
tests/test_bitbucket_cloud_oo.py

This fixes a bug that ends in missing data when using `pullRequests.each()`.
The pullrequests endpoint won't deliver the 
whole PullRequest object (e.g. participants, reviewers missing).
So we need to load all the data for the PR object.
The [docs](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/pullrequests) say:
> The list of users that were added as reviewers on this pull request when it was created. **For performance reasons, the API only includes this list on a pull request's self URL.**
After merging this PR the PullRequest API is still broken and needs to be fixed by #844

Fix missing data when using pullRequests.each()

---

atlassian/jira.py
docs/jira.rst

Signed-off-by: Graham Weldon <graham@grahamweldon.com>
adds `issue_delete_watcher` function.

Add functionality to delete a watcher from an issue

---

atlassian/jira.py
docs/jira.rst

Provides code and documentation for getting watchers for an issue.

Add function for getting watchers

---

atlassian/jira.py

Unlike in add watcher, the user parameter has to be handed over as query parameter, according to the documentation: https://docs.atlassian.com/software/jira/docs/api/REST/8.13.14/#issue-removeWatcher. This patch fixes this issue.

Fix delete watchers

---

atlassian/jira.py

Exception raised when requesting issue archive: requests.exceptions.HTTPError: 405 Client Error:
Addtionally, the api doesn't use notify_users as query parameter -
https://docs.atlassian.com/software/jira/docs/api/REST/8.1.0/#api/2/issue-archiveIssue

[JIRA] Update issue_archive method to match the current api

---

atlassian/jira.py

Implemented similar to the add issue to sprint method.

Add issues to backlog method added

---

atlassian/bitbucket/cloud/repositories/diffstat.py
atlassian/bitbucket/cloud/repositories/pullRequests.py

* Added object for DiffStat and moved to its own
file since it can be generated at different places
in the API.

Bitbucket Cloud: Add PR diff/patch/diffstat

---

atlassian/jira.py
docs/jira.rst

add an issue_editmeta method to Jira, (similar to the existing issue_createmeta) only for issues which already exist.

[JIRA] Add method to get an issue's edit meta

---

atlassian/jira.py

There was a function for the permission scheme but missing for notification scheme.

[JIRA] Add get_project_notification_scheme to jira.py

---

docs/jira.rst

get_project_issuekey_all(self, project, start=0, limit=None, expand=None): function by default doesn't specify any limitation with regards to number of returned results. 
However Even with limit=None flag API will return 50 maximum, when specific high limit number for example limit=200 only 100 results will be returned. This is due to the limitation on the  JIRA CLOUD API side  https://jira.atlassian.com/browse/JRACLOUD-67570 and https://community.atlassian.com/t5/Jira-Software-questions/Is-there-a-limit-to-the-number-of-quot-items-quot-returned-from/qaq-p/1317195.

Added warning ti get_project_issuekey_all function usage

---

atlassian/confluence.py

All other functions in confluence.py use rest/api/.
confluence.get_content_templates() works a lot better now.

[Confluence] Fixed template functions urls using wiki/rest/.

---

examples/jira/jira_oauth2.py

- added example code to implement jira cloud oauth2 integration

[JIRA] added jira oauth2 integration to examples

---

atlassian/crowd.py
docs/crowd.rst

Remove password autogeneration from user creation.
Secrets library is not supported till Python 3.6.
Fixes #913
Signed-off-by: Martin Styk <mart.styk@gmail.com>

[CROWD] Require password as an argument during user creation

---

atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/bitbucket/cloud/repositories/refs.py

Note that this currently does not support the generic
refs endpoint.

Bitbucket Cloud: Add branches and tags repository endpoints

---

.github/workflows/test.yml
Dockerfile.qa
atlassian/bamboo.py
setup.py

Adding support the next app:
#917

Add 3.10 python support badge and docker file

---

atlassian/jira.py

Properly escape Jira project key for JQL queries

---

atlassian/jira.py

Documentation for ```account_id``` parameter for ```assign_issue()``` is misleading for usage with ****Jira Server****.
When using Jira Server; ```assign_issue()```'s ```account_id``` parameter must take a valid Jira ````username````.
The parameter does  ****NOT**** take  a Jira Cloud ```account_id``` or Jira Server ```user_id``` as current docs for this project suggest when using Jira Server.
Reference materials for endpoint ```assign_issue()``` calls for Jira Server can be found [here](https://docs.atlassian.com/software/jira/docs/api/REST/8.5.0/#api/2/issue-assign).
```python
assign_issue(issue_key="EXAMPLE-1234", account_id="mzuckerberg")
``` 
Method documentation has been updated to avoid future confusion.

[Jira] document assign_issue() usage for Jira Server

---

atlassian/bitbucket/cloud/base.py

The default one in AtlassianRestAPI does not work
for Bitbucket Cloud.

Bitbucket Cloud: provide custom raise_for_status

---

atlassian/bitbucket/__init__.py
atlassian/bitbucket/base.py

Also the changes from #872 are merged into the copied code.
@gonchik What about switching all functions using the paged API to the `_get_paged` function. With this the parameters can be removed, but this will be a incompatible change. 
Closes #933

Use paged get for get_branch_permission.

---

setup.py

This path will only include the packages `atlassian*` in the release.
Closes #926
Closes #903 (this issue wasn't linked)

Remove tests folder from release.

---

atlassian/bitbucket/cloud/repositories/branchRestrictions.py

Both 'branch_type' and 'branch_match_kind' contained a typo adding 'string' which prevented them from working as intended.

fix 'string' typo

---

atlassian/bitbucket/__init__.py
atlassian/jira.py

It seems that, probably by accident, the `Jira.jql` method doesn't check for paging and, as a result, only returns the first page. This makes it properly retrieve all the pages.
We've been using this patch at my workplace for a while already, but I haven't opened a PR before due to being busy (lazy).
I'm not sure how to run the tests, or how to validate it with "black" as in the contributing instructions, please let me know if I need to fix something.

Fix paging when querying Jira via JQL

---

atlassian/bitbucket/cloud/repositories/diffstat.py

Conflicts due to file deletion and file rename
were not convered, yet. According to my tests
conflicts due to file addition get marked as
"merge conflict".

Bitbucket Cloud: Diffstat has more possibles states

---

atlassian/confluence.py
requirements-dev.txt
tox.ini

As suggested in #936 this PR adds a function to handle the paging.
ATTENTION: I've no instance to test it, it's only created from the API documentation. @hograthm or @gonchik can you test this?If it's working other calls of confluence can also be changed.

[Confluence] Add `_get_paged` function for internal handling of paged APIs.

---

CONTRIBUTING.rst

Hi,
I try to add some changes but one URL in the contributing file was wrong.
Probably a change from black maintainers.

DOC : correct URL for black tool in CONTRIBUTING.rst

---

atlassian/confluence.py

Confluence.py change to page_exists() function. Function will now make its own request and handle the response to determine the True or False value rather than utilising "self.get_page_by_title(space, title)" which outputs errors to the log if it cannot find a page.

[Confluence] page_exists method without error log

---

atlassian/insight.py

- updated to check for cloud parameter and trigger separate init process for seamless cloud-relevant configuration.
- sets api_root parameter for on-prem to allow for single method of building urls within insight.py
- updated to use url_joiner(api_root, <path>) for single pattern across cloud & on-prem
- added cloud check and NotImplementedError to methods that are not available with Insight Cloud
- uses __get_workspace_id to assemble api_root path
- sets default headers to `{'Accept': 'application/json'}`
- uses ServiceDeskApi to get InsightCloud workspace Id

[Insight] Update to support Cloud

---

atlassian/__init__.py
atlassian/insight.py

Just simple wrapper of Insight for Jira

added simple wrapper

---

atlassian/bitbucket/__init__.py

To only list files from a specific folder in the target repository, you can add it to the URL like so:
`.../projects/{project_key}/repos/{repository_slug}/files/{folder}
I added an extra parameter to the method, which will add the folder to the URL if given.

updated get_file_list method for folder support

---

CONTRIBUTING.rst
README.rst
atlassian/insight.py

Adding more methods since i have them written. I'll find some time soon to finish the rest.
Also added some light documentation updates.

[Insight] Adding More Methods

---

atlassian/jira.py

According to https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-user-properties/#api-group-user-properties, the user identifier for user property endpoints is "accountId", not "username".
This fixes the API for the endpoints:
- Get user property keys
- Get user property
- Set user property
- Delete user property

Jira: Fix user properties endpoints (use account id)

---

atlassian/service_desk.py
docs/service_desk.rst

Add to sd.get_request_comments params start, limit, public, internal as in https://docs.atlassian.com/jira-servicedesk/REST/3.6.2/#servicedeskapi/request/{issueIdOrKey}/comment-getRequestComments

[SD] request_comments start,limit,public,internal

---

atlassian/jira.py

Change URL creation to match other PUT commands.

Jira: Fix update_version PUT url

---

atlassian/jira.py

- create_agile_board method adapted for Jira Server
- associate an issue type scheme
- create a new issue type scheme
- create a new permission scheme
- add a field to a given tab in a screen

[JIRA] Add multiple methods

---

atlassian/rest_client.py

Our Jira cloud instance does not include "errors" field in some error responses:
```
{'errorMessages': ["The value 'ABC' does not exist for the field 'project'."], 'warningMessages': []}
```
This crashes the error processing with `KeyError: 'errors'`, and the client doesn't see the _actual_ error message.

Fix error response without 'errors' field

---

docs/bitbucket.rst

docs: rm duplicate param in `fork_repository()`

---

atlassian/bamboo.py
docs/bamboo.rst

This adds a method for deleting deployment projects from  bamboo.

Bamboo: Allow to delete deployment project

---

atlassian/confluence.py

Fixes: https://github.com/atlassian-api/atlassian-python-api/issues/989
When a page has more than 25 subpages, the method get_child_id_list and similar are throwing an exception about wrong URL (missing domain).
This is caused by the fact that` _get_paged` method is setting `absolute = True` where it should be `absolute = False`
As according to documentation the `_links.next` page URL is relative (the domain is returned in `_links.base` field in the response.

Make pagination work for fetching subpages of confluence page

---

docs/jira.rst

While this is small, it did confuse me at first and led me to believe this function is in the global namespace.

Update JIRA docs with missing prefix

---

atlassian/confluence.py

Confluence: Added the ability to create_page in confluence.py to set page full width. Default is False to make it how it is today.

Confluence: Add page width to page creation

---

atlassian/confluence.py

It seems like the confluence rest api has been updated. this pull request fixes the remove content history url.
https://developer.atlassian.com/cloud/confluence/rest/api-group-content-versions/#api-wiki-rest-api-content-id-version-versionnumber-get

[Confluence] remove content history

---

atlassian/jira.py

Find users who have access to browse issues in a project. Supplying a username=" " will return all the users who have browse permission to a project.
https://docs.atlassian.com/software/jira/docs/api/REST/8.20.11/#user-findUsersWithBrowsePermission

Find users who have access to a project to browse

---

atlassian/jira.py
docs/jira.rst

This PR is to add account_id to the parameters of add_user_to_group for Jira Cloud. Username of the parameters is no longer available for Jira Cloud. When the site url contains Jira Cloud one, account_id is used for the parameter. This PR is add version of this PR https://github.com/atlassian-api/atlassian-python-api/pull/1018 . For DC/Server users, there is nothing to change.

Jira : add account_id to the parameters of add_user_to_group for Jira Cloud 

---

docs/confluence.rst

Address [issue](https://github.com/atlassian-api/atlassian-python-api/issues/983) #983

[Confluence] Amending Confluence documentation

---

atlassian/__init__.py
atlassian/cloud_admin.py
atlassian/rest_client.py
docs/cloud_admin.rst
docs/index.rst
examples/cloud_admin/cloud_admin_orgs_get_organizations.py
examples/cloud_admin/cloud_admin_users_get_profile.py

Hi 
As talked here #1029, this PR creates new module Cloud Admin for following APIs. https://developer.atlassian.com/cloud/admin/about/
There are two sub modules, CloudAdminOrgs and CloudAdminUsers. In this PR, those are very basic feature such like "get profile" and "get organizations". 
Please let me know if there is any comments. 
Thanks

Add new module Cloud Admin

---

atlassian/bitbucket/cloud/repositories/__init__.py

[BlackTest] Reformatting file

---

atlassian/jira.py

This PR closes #1030 
Adds new functions to maintain the same level of functionality, while also adding a deprecation warning for the old function.
To learn more about why this is needed, check out https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html
TODO:
- May be best to use the `self.resource_url` function for consistency's sake

Add new createmeta functions to comply with Jira 9 API

---

atlassian/jira.py
docs/jira.rst

Hi
This PR adds function get_user_groups which is only available for Jira Cloud platform. Jira DC/Server doesn't have this API.
Thanks

[Jira] Add function get_user_groups

---

atlassian/jira.py
docs/jira.rst

Adds two parameters to `Jira.create_or_update_issue_remote_links` to support adding icons to remote links:
```
"object": {                                            
"url":"example.com/support?id=1",     
"title":"TSTSUP-111",                                 
"icon": {                                         
"url16x16":"https://example.com/favicon.png",    
"title":"Support Ticket"   
},
```
see descriptions of these fields [here](https://developer.atlassian.com/server/jira/platform/using-fields-in-remote-issue-links/).

Jira: Add ability to add icons to issue remote links

---

atlassian/bitbucket/cloud/repositories/__init__.py

This allows to access a Repository object without having
access to the workspace endpoint.

Bitbucket Cloud: allow to access repositories directly

---

atlassian/service_desk.py

Adds the missing `.json()` Response method in order to _transform_ the response object into a python dictionary.

Fix AttributeError: 'Response' object has no attribute 'get'

---

atlassian/rest_client.py

Fix for https://github.com/atlassian-api/atlassian-python-api/issues/1005

Switch from SHA1 to SHA2

---

CONTRIBUTING.rst

The Bamboo REST API documentation has been moved to a new URL.

[Bamboo] New Bamboo REST API documentation URL

---

atlassian/confluence.py
docs/confluence.rst

On Confluence cloud, the experimental API for `get_content_history_by_version_number` does not work. By changing `rest/experimental/content/` to `rest/api/content/`, it works normally.
Fixes #960 raised by @yvespelle

Move API from experimental to normal url (#960)

---

atlassian/jira.py
docs/jira.rst
examples/jira/jira_get_comment.py
tests/responses/jira/rest/api/2/comment/list/POST
tests/responses/jira/rest/api/2/issue/FOO-123/comment/10000/GET
tests/responses/jira/rest/api/2/issue/FOO-123/comment/GET
tests/test_jira.py

Implement:
- issue_get_comments(issue_id)
- issue_get_comment(issue_id, comment_id)
- issues_get_comments_by_id(comment_id, [comment_id ...])

Jira: Add functionality to get comments on an issue

---

README.rst

Use of print is valid and the correct thing for this example (pretty-print-usage)
```
pprint(jira.issue('INT-1'))
{'expand': 'renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations,customfield_10010.requestTypePractice',
'fields': {'aggregateprogress': {'progress': 0, 'total': 0},
'aggregatetimeestimate': None,
'aggregatetimeoriginalestimate': None,
'aggregatetimespent': None,
'assignee': None,
'attachment': [],
'comment': {'comments': [{'author': {'accountId': '557058:dc675182-d776-46f5-90fb-fe5637b71397',
'accountType': 'atlassian',
'active': True,
'avatarUrls': {'16x16': 'https://secure.gravatar.com/avatar/6f1cc3b97033de549f9d156d0eea4a34?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-4.png',
'24x24': …
```

Revert change: `pprint` to `print` ... `pprint` 

---

atlassian/confluence.py

* Fix def get_page_as_pdf using requests lib def get
* Fix def get_pdf_download_url_for_confluence_cloud
I am using Confluence Cloud.
So, I don't check Confluence.
in consideration of other factor,
Return Using request.get immediately after `if  self.api_version == "cloud":` in def get_page_as_pdf

[confluence] Fix def get_page_as_pdf When using Confluence Cloud(#1057)

---

atlassian/rest_client.py

While fetching issues from the Atlassian Cloud API, it is common to hit the Rate Limit of Atlassian. If you want to handle the retry with the `Retry-After` header, you need the raw response of the request. Currently, it was only possible to enable advanced mode for the full class, but was missing the advance mode in the method. 
While advanced mode was already added to the `get` method, it was not passed to the `request` method.
This PR adds a convenience option to the underlying request method, turned off by default, to enable advance mode.

Add missing advanced mode to request method

---

README.rst
atlassian/bitbucket/cloud/repositories/pipelines.py
tests/test_bitbucket_cloud_oo.py

`return None` instead of response

Resolve Failing Tests: Correction to adanced_usage=True

---

.github/workflows/test.yml

Update checkout and codecov action to use NodeJS 16 (https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).

Update checkout and codecov action

---

tests/test_confluence_attach.py

Replace deprecated `tempfile.mktemp()` calls with `mkstemp()` ([docs](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp)).

Replace deprecatd tempfile.mktemp() calls

---

atlassian/jira.py
docs/jira.rst

Added request_current_index_from_node method and docs for the cluster methods

Added request_current_index_from_node method and docs

---

atlassian/bamboo.py
atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/rest_client.py

As long as Python 2.7 support is maintained, it should at least be importable without  SyntaxErrors, even if full functional testing is not part of the CI.

Python 2.7 compatibility

---

atlassian/confluence.py

Add the type parameters when judging whether a page exists, such as blogpost, page

Add the type parameters whether a page exists

---

atlassian/bitbucket/cloud/repositories/pullRequests.py

Closes [this issue](https://github.com/atlassian-api/atlassian-python-api/issues/1100).
Updated `pull_requests.comments` to accept optional query string and sort parameters, which are added to `params` if present and used with `_get_paged`.
Logic was copied from `PullRequests.each`, which already accepts query string and sort parameters.

[Bitbucket Cloud] Add support for query parameters in pullrequest.comments endpoint

---

atlassian/jira.py

Issues for backlog is using the incorrect URL according to this documentation: 
* https://docs.atlassian.com/jira-software/REST/7.0.4/#agile/1.0/board-getIssuesForBacklog
* https://developer.atlassian.com/cloud/jira/software/rest/api-group-board/#api-rest-agile-1-0-board-boardid-backlog-get resulting in HTTP 404
Fixes: _#1103_

[Jira] Issues for Backlog updated URL

---

atlassian/confluence.py

To get all the all the pages need to pass all the details related to next traversal

Returned _link details for next loop

---

atlassian/bamboo.py
docs/bamboo.rst

Atlassian introduced 2 endpoints to enable and disable elastic bamboo
`Get admin latest elastic config
GET /rest/admin/latest/elastic/config`
`Put admin latest elastic config
PUT /rest/admin/latest/elastic/config`

[Bamboo] Enable/disable elastic bamboo configuration

---

atlassian/insight.py

Hi!
I get an error when trying to get objecttype attributes via this lib.
The was occurred because of invalid link generation - just miss a slash in generated url:
https://jira.insight.url/rest/insight/1.0objecttype/1/attributes'

Fix API url for getting objecttype attributes

---

atlassian/service_desk.py

In service_desk.py/attach_temporary_file a check was added to successfully post the request. fixes #1056
If advanced mode is set the raw response must be converted to json, not so in normal mode.

Jira ServiceDesk: Fix create attachment

---

atlassian/jira.py

added logic to add_attachment function

Update jira.py add_attachment method

---

atlassian/rest_client.py
atlassian/statuspage.py

Working on statuspage.io wrapper here!
- Documentation: https://developer.statuspage.io/
- Docstrings type: NumPy
----
Upon merge close issue #1026.

Add support for statuspage.io

---

atlassian/confluence.py

This will give you a fixed-width page.

This will give you a fixed-width page.

---

atlassian/jira.py

adds some convenience functions to label and unlabel issues.  tested with jira cloud.

feat: label and unlabel issues

---

atlassian/confluence.py

Goal of this PR:
- Update `get_page_by_title` to support blogpost too.
- Update `get_page_by_id`  to support blogpost.

[Enhancement] Add support for fetching id of blogpost

---

setup.cfg

**When installing  atlassian-python-api==3.35.0 (python version 3.9.6)**
**The following warning occurrend and prevented the following installing.** 
UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
**Raw log like this:**
(.gitbot) [root@g]# pip install -r requirements.txt 
Collecting atlassian-python-api==3.35.0
Downloading atlassian-python-api-3.35.0.tar.gz (144 kB)
|████████████████████████████████| 144 kB 820 kB/s 
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing wheel metadata ... error
ERROR: Command errored out with exit status 1:
command: /root/gitbot/.gitbot/bin/python3 /root/gitbot/.gitbot/lib/python3.9/site-packages/pip/_vendor/p …

'description-file' will not be supported in future versions.

---

atlassian/service_desk.py
tests/test_servicedesk.py

There's a spelling inconsistency of 'organisations'.  This PR adds `service_desk.get_organizations()` as an alias of `get_organisations()` to maintain compatibility while allowing for correct spelling.

Alias get_organizations

---

atlassian/rest_client.py

RSA_SHA512 was hardcoded in the REST Client for OAuth1. It is now possible to change the 'Signature Method' in the 'oauth_dict' with the key 'signature_method' to another signature. The default value is kept as 'SIGNATURE_RSA' if no value for the mentioned key is provided.

Add the possiblity to change the signature method

---

atlassian/confluence.py

TLDR; 
Atlassian recently updated Confluence's PDF export functionality.
**Here's the current flow works:**
1.  Create a pdf page export task using the `spaces/flyingpdf/pdfpageexport.action?pageId={pageId}` endpoint.
2. In the next step, use the poll endpoint, `runningtaskxml.action?taskId={taskId}`, to determine whether the export task has been completed.
3. Retrieve the download URL from the poll endpoint response if the task was successfully completed
4. Get the PDF data from the retrieved endpoint.
**Step 2 seems to be where the issue appears:**
- It does not matter if the task is successfully initialised or not, the poll endpoint will report that the task does not exist without raising an error message.
- As a result, step 3 queries the space URL without a specific page.
- …

[Confluence]: PDF export function no longer working #1158 BUGFIX

---

atlassian/rest_client.py
tests/responses/jira/rest/api/2/issue/POST
tests/test_jira.py

Since I don't know if the original code was supposed to support specific response bodies, I decided to keep the original behaviour and add safety checks for the responses that we receive from Jira in 400 responses.

Fix #1154: add safety checks to parse 400 error responses

---

atlassian/bamboo.py

Added 2 methods:
1. `get_deployment_projects_for_plan(plan_key)`
This uses the `GET /rest/api/latest/deploy/project/forPlan` API to fetch all the deployment projects associated with a plan.
2. `trigger_deployment_for_version_on_environment(version_id, environment_id)`
This uses the `POST /rest/api/latest/queue/deployment` API to trigger a deployment of a release on an environment.
`make docker-qa` runs successfully with no issues.
Tested on local Bamboo server instance.

Bamboo: Added 2 methods to bamboo for deployments

---

atlassian/bitbucket/cloud/repositories/pipelines.py

This PR enables custom target pipeline types when triggering the bitbucket cloud pipeline.  When the user needs to call a specific pipeline of a given branch.

Adds features to specify the target pipeline type.

---

atlassian/confluence.py

Based on new API endpoints provided in Confluence DC 8.2

Update confluence.py - Add create_group and remove_group

---

examples/jira/jira_add_label_tag.py

fix spelling error in jira_add_label_tag.py for Jira examples

Jira: jira_add_label_tag example

---

atlassian/confluence.py

The Code in `get_pdf_download_url_for_confluence_cloud` checks for errors in the PDF Export like this:
```
if percentage_complete == 100:
running_task = False
log.info("Task completed - {task_state}".format(task_state=task_state))
if task_state == "FAILED":
log.error("PDF conversion not successful.")
return None
log.debug("Extract task results to download PDF.")
task_result_url = progress_response.get("result")
else:
…
```
However, pages can fail at any percentage, leading to repeated checks (which never complete):
```
INFO:atlassian.confluence:50% - FAILED
INFO:atlassian.confluence:Check if export task has completed.
INFO:atlassian.confluence:50% - FAILED
INFO:atlassian.confluence:Check if export task has completed.
…
```
This change makes the code check the Task-State at every …

confluence: correctly report a failed pdf-export

---

atlassian/confluence.py
docs/confluence.rst

Adding a function for the following methods:
- changeUserPassword
- changeMyPassword
https://developer.atlassian.com/server/confluence/remote-confluence-methods/
Still need to update docs

Adding change password to confluence.py

---

atlassian/bitbucket/__init__.py

This PR adds two parameter (until, since) on get_commits which is only available for Jira Server.
Thank you.

[Jira] Commits parameter addition for until and since

---

atlassian/bitbucket/__init__.py

Retrieve a page of pull requests where the current authenticated user is involved as either a reviewer, author or a participant. The request may be filtered by pull request state, role or participant status.
https://developer.atlassian.com/server/bitbucket/rest/v811/api-group-dashboard/#api-api-latest-dashboard-pull-requests-get

Bitbucket Server: Add API to get dashboard pull requests

---

atlassian/jira.py
docs/jira.rst

This PR introduces two small changes for the Jira remote links creation:
1. fix: icons for remote links were incorrectly nested and therefore ignored by Jira
2. feat: add status resolved for setting link as resolved (strikethrough yes/no in Jira)

[Jira] Adapt issue remote links creation/update

---

atlassian/bitbucket/__init__.py
docs/bitbucket.rst

Also add separate API to get required reviewers for a PR
See https://developer.atlassian.com/server/bitbucket/rest/v811/api-group-pull-requests/#api-default-reviewers-latest-projects-projectkey-repos-repositoryslug-reviewers-get

Bitbucket Server: Add support to include required reviewers for PR

---

atlassian/rest_client.py
tests/mockup.py
tests/responses/jira/rest/api/2/issue/POST
tests/test_jira.py

This should solve #1230.
I tried to straighten out the code a bit.
I am not sure why we checked if the key from .items() is a dict. That is not possible.
```python
tdk = {"hello": "world"}
td = {tdk: "cool it works"}
Traceback (most recent call last):
File "<string>", line 1, in <module>
TypeError: unhashable type: 'dict'
```
I guess in an earlier version we iterated over a presumed dict and named the variable k(for key) (But in the background it was a list). https://github.com/atlassian-api/atlassian-python-api/commit/fc620ae094c162f36d93ceaa0998ebbc1ca9bf20 
Then it was modified. But they then stopped iterating over the object but iterated over the items, which are apparently not always present. https://github.com/atlassian-api/atlassian-python-api/commit/4bb337a5d262912d6459d12d51aecf54 …

lists and dicts can be handled in raise_for_status

---

atlassian/rest_client.py

**Background**
Some Jira instances have been configured behind reverse proxies that require a client certificate for authentication to even hit the server. The `requests` library that is used by the connection library allows a `cert` property for this client authentication.
**Change**
- Add the keyword argument property (`cert`) to the `AtlassianRestAPI` class that is passed to an instance variable and passed to the `session.request(...)` function
**References**
- https://docs.python-requests.org/en/latest/user/advanced/#client-side-certificates

Add `cert` Property Request

---

docs/bitbucket.rst

The documentation lists "groupname" as the parameter accepted by project_grant_group_permissions, but group_name is expected:
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket/__init__.py#L500

Documentation: Bitbucket project_grant_group_permissions parameter

---

atlassian/jira.py

Now using the 'resource_url' function to work with 'api_version' configuration.
Added a new function to get a list of deleted worklogs.

Jira: updated worklog urls

---

atlassian/rest_client.py

#1241 
added propagation of the `advanced_mode` flag for `put`, `post`, `patch`, and `delete` functions.  Prior to this change, the `advanced_mode` flag was only propagated to the `request` method for `get` calls.  The `advanced_mode` `requests.Response` object is very useful in having code gracefully handle rate limit 429 responses from the server since the response headers will include the necessary backoff information that the client should use before making another request.

[ISSUE-1241] #1241, added propagation of `advanced_mode` flag 

---

atlassian/rest_client.py

if keys or values in the response json are `int`s, the `k + ": " + v` expression will fail because an `int` is not a `str`.  In order to avoid this, we can either use `%`-formatting, `.format` formatting, or f-strings.  I chose f-strings for usability, but regardless of which direction, the issue should be addressed one of those ways.
addresses #1242

[ISSUE-1242]  prevented weird exceptions related to integer handling

---

atlassian/insight.py

I experienced 415 error messages due to missing headers when making put and post calls to Assets in cloud.

Add Content-Type to calls to Assets in cloud

---

atlassian/service_desk.py
docs/service_desk.rst

Due to deprication of usernames in Jira Cloud the option to use accountid when updating requestparticipant is required.
https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/

Add account list to request participant methods

---

Dockerfile.qa
tox.ini

Fixes the Python 3.12 CI build (see #1262).
The flake8 version used in the CI build is quite old, but an upgrade is blocked by `flake8-no-fstring` (needs flake8<4). An update to the latest version isn't possible as flake8 6.x does no longer support Python 3.6 and 3.7.
Are `importlib-metadata` downgrade and `flake8-no-fstring` still necessary? The later should be fixed by recent flake8 versions.

Fix Python 3.12 build

---

atlassian/jira.py
docs/jira.rst

* Migrate "get all projects" methods to use paginated endpoint for Jira Cloud.
* Update docs.
* Use the correct method in the archive project method.

[Jira]: Migrate get all projects methods to use paginated endpoint for Jira Cloud.

---

atlassian/jira.py

Currently, the user_get_websudo method is throwing an 'Expecting value: line 10 column 1 (char 9)' exception because of the lack of not_json_response parameter not being passed in the user_get_websudo method. Pushing this PR to fix this issue

Updating user_get_websudo to set the not_json_response as true #1267

---

atlassian/jira.py
docs/jira.rst

To fix #1273, rename the parameters of `Jira.tempo_4_timesheets_find_worklogs` as follows:
- `from` → `date_from`
- `from` is a keyword, so it cannot be used as a parameter name
- `date_from` is also used in `Jira.tempo_timesheets_get_worklogs`
- See https://github.com/atlassian-api/atlassian-python-api/issues/1273
- `to` → `date_to`
- renamed for consistency with `date_from`

Jira: Rename tempo_4_timesheets_find_worklogs params (#1273)

---

atlassian/jira.py
docs/jira.rst

`update_issue_field` method can utilize `"notifyUsers"` query parameter to enable/disable email notification. 
https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-put
So does `issue_edit_coment` method as well.
https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-comments/#api-rest-api-2-issue-issueidorkey-comment-id-put

JIRA: Add `notify_users` option to 2 methods

---

atlassian/confluence.py
docs/confluence.rst
examples/confluence/confluence_get_tables_from_page.py
requirements.txt
tox.ini

* Added new method  get_tables_from_page . Method gets page body content and scraps from it all tables present on the  page. 
* Tested with confluence cloud API
* Two additional dependencies added bs4 and lxml 
* I also added bs4 to tox.ini file (otherwise make qa will fail -tox won't be able to ind the package that is listed in requireements.txt file

[Confluence] new method added confluence get_tables_from_page 

---

.readthedocs.yml
atlassian/crowd.py
docs/crowd.rst
requirements-dev.txt
requirements.txt
setup.py

- Add a new function `user_groups` used to get specify user's all group info
- Introduce new dependencies `jmespath` which is used for search string in json, for more info, read: [JMESPath Tutorial — JMESPath](https://jmespath.org/tutorial.html)
- Using universal request to get user's group, controled by `kind` param
- Using universal request to get group's member, controled by `kind` param
- Add a new function to determine whether the user is a member of a group
- Add a parameter `max_results` has prevented insufficient results from being returned, the server default is `1000`

Add more Crowd functions

---

docs/confluence.rst

The docs mention a function with the name `download_attachments`, but this function does not exist. This doc entry was added in #1283 which also adds the function `download_attachments_from_page`. I assume it's a simple mistake in the docs, so here a PR to update the docs.

Fix download_attachments_from_page documentation

---

docs/index.rst

This is just a small contribution for the docs to help clarify the usage of Confluence Token in OnPrem Server and Data Center versions.
It should close this Issue and help clarify wrong informations:
#911
It relates to these two tickets since there are also some informations about the login Process that are missguiding:
#1070 
#332

[confluence] documentation of token authentication

---

atlassian/confluence.py

Add possibility to remove a space permission. Uses the JSON RPC interface.
Not implemented for cloud.

add remove_space_permission

---

requirements.txt
tox.ini

As noted at https://pypi.org/project/bs4/, the official name of the Beautiful Soup package is beautifulsoup4, while bs4 is just an alias. In distribution packaging (such as Fedora) the package may not be available under this alias, so it's better to use the official name.

Use correct name for Beautiful Soup in dependencies

---

setup.py

Let's define `install_requires` inside `setup.py` out of `requirements.txt` file.
We keep then only one source of dependencies and we let build fail early (on wheel build) if `requirements.txt` contains wrong dependencies.

 Use requirements file for install_requires

---

setup.py

`setup.py` was ditched a long time ago and newer PEPs recommend using `setup.cfg` or `pyproject.toml`
The last changes in `setup.py` created a misdirected dependency between `requirements.txt` and `setup.py`, which included an optional dependency that is causing problems upstreams.
This PR merely reverts those changes in favour for the old already-working setup.

revert misuse of programmatical approach in setup.py

---

atlassian/jira.py
docs/jira.rst
examples/jira/jira_get_comment.py
examples/jira/jira_oauth2.py
examples/jira/jira_scrap_regex_from_issue.py

* Added new method to jira api scrap_regex_from_issue.
*  This method takes issue_id as an input + specified regex and returns all regex matches found in issue comments and descriptions.
* Commits also includes docs + examples.
* have tried to cover this feature with unit test but I didn't manage to make use of mockup files when using method patching:
` 
try:
from unittest.mock import patch, MagicMock
except ImportError:
from mock import patch
def test_scrap_regex_from_issue(self):
regex = r"((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)[?.]?){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
mock_without_comments = "< saved output from api1>"
mock_with_comments = "< saved output from api2>"
with patch("atlassian.Jira.get_issue") as mock_get_tables:
mock_get_tables.return_value = mock_without_comments …

[jira] new feature added scrap_regex_from_issue + docs + example

---

atlassian/bitbucket/__init__.py

Non existing API endpoint was used in the latest version, so this PR fixes that.

Fixed Pull Requests Activities path

---

examples/jira/jira_edit_issue.py

Added an example for `jira.edit_issue`

Examples of updating a issue using operations

---

atlassian/jira.py

Used for fetching a specific version if the id is known and used to reposition the versions without having to go through the awful UI to do so.

Added get_version and move_version

---

atlassian/bitbucket/__init__.py

The latest release of the atlassian-python-api package modified the pull_request_activities url to use the `activity` endpoint which matches the [Bitbucket Cloud API](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pullrequests/#api-repositories-workspace-repo-slug-pullrequests-activity-get). However, the latest [Bitbucket Server API](https://developer.atlassian.com/server/bitbucket/rest/v818/api-group-pull-requests/#api-api-latest-projects-projectkey-repos-repositoryslug-pull-requests-pullrequestid-activities-get) still uses the activities endpoint. These changes fix the method to switch between the two endpoints as appropriate using the `cloud` attribute.

[Bitbucket] Split pull request activities url for Cloud and Server

---

atlassian/rest_client.py

#1337 New line character issue on linux environment
Below are the test results [ALL PASSED]
```bash
> make qa
tox
py3: install_deps> python -I -m pip install beautifulsoup4 coverage pytest pytest-cov requests
.pkg: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel
.pkg: _optional_hooks> python /Users/ashishpatel/workspace/atlassian-python-api/venv/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /Users/ashishpatel/workspace/atlassian-python-api/venv/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_wheel> python /Users/ashishpatel/workspace/atlassian-python-api/venv/lib/python3.11/site-packages/pyproject_api/_back …
```

Issue 1337: Bearer token on linux environment has new line character

---

atlassian/rest_client.py

Uses the urllib3 builtin Retry mechanism.
We only support retrying on HTTP return status,
not on any of the other retries that that class
defines (e.g. connection problems, redirects).
The usual use case for this is to handle 429
responses from the Atlassian Cloud API which
has request limits that are easily hit by
scripts iterating over objects like Jira
issues or Bitbucket pull requests.
Based on earlier work by @jp-harvey.
Replaces #904

[Rest] Support exponential backoff and retry

---

atlassian/jira.py

[Jira] fix paginated projects retrieving

---

atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/bitbucket/cloud/repositories/hooks.py
docs/bitbucket.rst

Support CRUD operation of BitBucket Cloud repository webhooks based on the following endpoints:
[Create webhook](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-hooks-post)
[Get webhook](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-hooks-uid-get)
[Update webhook](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-hooks-uid-put)
[Delete webhook](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-hooks-uid-delete)

[BitBucket] Add webhooks to Cloud

---

atlassian/jira.py

Add a generic method for paging in the cloud.

[Jira] Fix paged projects

---

.github/workflows/codeql-analysis.yml
.github/workflows/test.yml

Updates all GH Actions to their latest release which fixes deprecation warnings:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
CodeCov introduced the requirement for an upload token ([breaking changes](https://github.com/codecov/codecov-action/blob/main/README.md#breaking-changes)). Please see [documentation](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions) or  [usage guide](https://github.com/codecov/codecov-action/blob/main/README.md#usage) for how to configure it.

Update GH Actions and fix NodeJS16 deprecation warnings

---

atlassian/bitbucket/__init__.py
docs/bitbucket.rst
examples/bitbucket/bitbucket_groups.py

added a new method to the Bitbuckets get_groups which:
* Takes a  display name for the group as input.
* Returns a list of user groups.

[BitBucket] added new method get_groups + docs + examples

---

atlassian/rest_client.py

This PR fixes missing JIRA error msg, related to #1363
Error handling can also be simplified as follows:
```python
if 400 <= response.status_code < 600:
raise HTTPError(response.text, response=response)
else:
response.raise_for_status()
```

fix missing error msg

---

.readthedocs.yml
atlassian/jira.py

This makes get_issue_changelog work by calling the URL that is pagable and sending the parameters on the url get.
This is a breaking change as the return structure of `/issue/<key>/changelog` is different from the return structure of `/issue/<key>?expand=changelog`,

[Jira] Make get_issue_changelog start and limit work.

---

atlassian/confluence.py
atlassian/jira.py

`get_draft_page_by_id` calls the same endpoint as `get_page_by_id` but with the status defaulted to `draft`. Updated the underlying function to just forward the params to `get_page_by_id` which allows the `expand` and `version` parameter to be passed as well, though I only added the `expand` parameter to `get_draft_page_by_id` since the versioning is a bit different than the standard page versioning.

[Confluence] Expand parameter addition for get_draft_page_by_id

---

atlassian/confluence.py

To be able to download more than the default number of attachments, the parameter "limit" (and also "start") should be added to the method download_attachments_from_page.

[Confluence] forward start and limit for getting attachments

---

atlassian/jira.py

Jira: Cloud and Server version diff request for changelog

---

atlassian/crowd.py
docs/crowd.rst

Add a new property of class `Crowd`, can retrieves full details of all group memberships, see: https://docs.atlassian.com/atlassian-crowd/5.3.1/REST/#usermanagement/1/group-getAllMemberships

Add `Crowd` a new attr

---

atlassian/crowd.py

- Fix `lxml` CVE, using `bs4` to replace.
- Add a property for Crowd class to retrieves full details of all group memberships.

Add a new property of `Crowd` class

---

atlassian/jira.py

The argument `paging_workaround` was added by accident. Remove it.
Close #1397

Remove unused kwarg

---

pyproject.toml
requirements-dev.txt
requirements.txt

This PR cleans up a couple of items which should help get a first-time contributor setup a little quicker.
Fixes #1411

Contribution cleanup

---

atlassian/rest_client.py

We are trying to use `backoff_and_retry` but are getting errors with urllib3 1.26.X this fixes and sets the minimum of `urllib3` to `>= 2.0.0`
The first release supporting `backoff_jitter` in the `Retry` class is the `2.0.0` release.
https://github.com/urllib3/urllib3/releases/tag/2.0.0
It doesn't look like this will be added to `1.26.X` https://github.com/urllib3/urllib3/pull/2952#issuecomment-1523888273

rest client: Only enable `backoff_and_retry` if `urllib3` is at least 2.0.0

---

atlassian/jira.py

Using the method `get_attachment_content()` returns a `str` of the content, which corrupts the actual content bytes due to encoding issues.
Assuming, there's a PNG image attached to a ticket, in my use case I want to download the PNG image.
```python
content = jira.get_attachment_content(12345)
with open("content.png", 'wb') as f:
f.write(content)
```
This leads to a runtime exception: `a bytes-like object is required, not 'str'`
IF I try to use text file mode `open("content.png", 'w')` then the content is broken due to utf-8 encoding, which is obviously not required, but used due to the fact the content object type is `str`.
Don't convert an attachment content into a string, e.g. using `self.get(url, not_json_response=True)`
* This PR fixes the issue for all binary attachments and is the …

[Jira] Fix get_attachment_content() return the content as `bytes` instead of `str`

---

atlassian/bitbucket/__init__.py

Hello there,
I recently discovered this library, nice work btw, and wanted to use it to automate some CICD in my company.
When trying to merge pull requests I noticed that merge_pull_request method was failing, after some investigation and searching in Bitbucket API docs I found that some parameters were missing from the POST body --> [source](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pullrequests/#api-repositories-workspace-repo-slug-pullrequests-pull-request-id-merge-post-request-body)
This PR aims to add these parameters. I took the liberty of also adding type hints and validation via Enum class for the MergeStrategies, hope this is okay with you.
I ran `make qa` and here is the final output:
```
doc8: commands[0]> doc8 --ignore-path docs/_build/ docs/
Scanning... …
```

Bitbucket: update merge_pull_request method to add merge_message, close_source_branch and merge_strategy parameters

---

atlassian/bitbucket/__init__.py

Hello there 🖖 
I was testing this in my local and Bitbucket Cloud was raising an error code whenever I tried to merge a PR.
Wanted to maintain previous version and did not notice that `params` dict was being sent as URL encoded params. The new params should be a JSON encoded body for the POST request instead --> [source](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pullrequests/#api-repositories-workspace-repo-slug-pullrequests-pull-request-id-merge-post)
I've fixed it and tested with my own repositories in Bitbucket Cloud 👍 
QA:
```Markdown
doc8: commands[0]> doc8 --ignore-path docs/_build/ docs/
Scanning...
Validating...
========
Total files scanned = 9
Total files ignored = 0
Total accumulated errors = 0
Detailed error counts:
- doc8.checks.CheckCarriageReturn = 0
- …
```

Bitbucket: fix merge_pull_request. POST`params` --> `data`

---

atlassian/service_desk.py

The default AtlassianRestAPI exception handler raises an HTTPError with an empty error message when using the Service Desk API.
The dedicated exception handler attempts to get the error message from the "errorMessage" (singular) property instead of the "errorMessages" (plural) property

Service Desk: add dedicated error handler

---

atlassian/confluence.py

Rel: https://github.com/atlassian-api/atlassian-python-api/issues/1422
The URL of the confluence REST API was wrong in add_user_group and it has to be a PUT request according to: 
[https://docs.atlassian.com/ConfluenceServer/rest/8.2.0/#api/user/{username}/group/{groupName}-update](https://docs.atlassian.com/ConfluenceServer/rest/8.2.0/#api/user/%7Busername%7D/group/%7BgroupName%7D-update)

Fixed confluence add_user_group to use right URL

---

atlassian/jira.py
tests/responses/jira/rest/api/2/issue/FOO-123/remotelink/POST
tests/test_jira.py

Adding a link to an application connected with a Jira instance through the `/rest/api/2/issue/{issueIdOrKey}/remotelink` Jira API route, an `application` section might be provided.
This might for instance be used to add Confluence links to a connected Confluence instance.
Cf. [Atlassian knowledge base about the different kind of links](https://confluence.atlassian.com/jirakb/how-to-use-rest-api-to-add-remote-links-in-jira-issues-1206556936.html).
This PR add an `application` parameter to the `create_or_update_issue_remote_links` function.

Add: Remote link: Application

---

atlassian/jira.py
tests/responses/jira/rest/api/2/issue/FOO-123/remotelink/POST
tests/test_jira.py

Reverts atlassian-api/atlassian-python-api#1429
Test have to be rewritten

Revert "Add: Remote link: Application"

---

atlassian/jira.py
atlassian/rest_client.py

Relevant to #1137, #501
A couple methods in Jira use chained method calls to retrieve data immediately after querying the API. For example, the `get_issue_link_types` method returns the data with the following line:
https://github.com/atlassian-api/atlassian-python-api/blob/e9520ab3957350f7f50293b514a242e61d54e11b/atlassian/jira.py#L3184
With advanced mode off, this is no problem because the first `.get` call returns a dictionary upon which the next `.get` operates. However, with advanced mode on, the result of the first `.get` is a `requests.Response` object. This class has no `.get` method, leading to the following error:
```
AttributeError: 'Response' object has no attribute 'get'
```
This PR adds a helper method in the underlying `AtlassianRestAPI` object, `_get_response_content` to …

[Jira] Fix get method data retrieval failures when advanced mode is on

---

atlassian/confluence.py

Default status is 'current' - that creates page as usual.
If pass 'draft' - page will be created as Draft, not visible in the tree with access by direct link or by managing recent drafts.

[Confluence] Add option to create draft page

---

atlassian/confluence.py

Add `expand` in params as `rest/api/content/search` url supports expanding

[Confluence] Add expand option to get_all_pages_by_label

---

atlassian/confluence.py

I recently was tasked with bulk exporting metadata about all pages in specific spaces and found out there's a perfect endpoint for that.
It just was not available in the library.

Confluence: Add function get_all_pages_by_space_ids_confluence_cloud

---

Makefile
tox.ini

As mentioned in #1460 here's a PR adding the `docker-fmt` target to make for invoking black more easily

Infrastructure: `make docker-fmt` for invoking black

---

.github/workflows/test.yml
Dockerfile.qa

Adds a Python 3.13 CI build.
For whatever reason curl was no longer installed.

Python 3.13 support

---

atlassian/bitbucket/__init__.py
atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/confluence.py
atlassian/jira.py

Avoid Python 3-only capabilities:
- Remove f-strings (jira.py, confluence.py)
- Remove type specifications (bitbucket)
- Remove trailing commas (bitbucket)

Continue to support Python 2

---

atlassian/confluence.py

Added the same fix done for get_content_history_by_version_number to attachment functions for cloud servers.
This also solves issue: #1139

Confluence: add cloud support for attachment functions

---

atlassian/bitbucket/__init__.py
docs/bitbucket.rst

new BitBucket Server methods for:
- assign_pull_request_participant_role
- add_pull_request_blocker_comment
- search_pull_request_blocker_comment

[BitBucket] add PR  related methods: blocker-comments and assign participant role

---

atlassian/confluence.py

adding a new function currently not provided by the api

Confluence: added possibility to share news based on a confluence page

---

atlassian/rest_client.py

Check for Retry-After and retry after that period.
Fixes: https://github.com/atlassian-api/atlassian-python-api/issues/1289

Support HTTP 429 Retry-After

---

atlassian/confluence.py

Double space inside the comment in `get_space_export ` was removed.

Removed double space in the comment inside get_space_export method

---

atlassian/rest_client.py

Adds the provided proxies to the request session after creation.
Without this the proxies will not be used to download attachements for example.

[Atlassian] Issue of not using proxies inside rest client session

---

atlassian/bitbucket/cloud/base.py

[Bitbucket] Fixed error_msg concatenation error in raise_for_status

---

atlassian/rest_client.py

After updating the library to version 3.41.18, the request method stopped working correctly due to the absence of the "Retry-After" header in the Confluence response.
I was getting a KeyError when the response had a status code of 429.
I also decided to add backoff_and_retry support with urllib3 < 2 version, since someone else might be using urllib3 <2. I think this would be a more expected behavior if, when enabling the backoff_and_retry function with urllib3 version <2, it worked anyway.

[Rest] Support exponential backoff and retry with urllib3 < 2 and new retry parameters

---

atlassian/bitbucket/cloud/repositories/commits.py

Resolves https://github.com/atlassian-api/atlassian-python-api/issues/1443

[Bitbucket] Add "get pullrequests by commit" method

---

atlassian/jira.py

Resolves https://github.com/atlassian-api/atlassian-python-api/issues/1478
Can anyone test this, please?

[Jira] Add update_permissionscheme method

---

atlassian/xray.py
docs/xray.rst

When my token is incorrect in XRAY, it raises a requests.exceptions.HTTPError, leaving me guessing as to where I go wrong. This could solve #1059 and #1159 , but I haven't got much information on these issues. Also, I'm unaware as to if the error is spread over more components, I only have experienced it in XRAY.
I also think the get_test_run_iteration method is necessary to get specific step information, such as parameters, etc. which the get_test_runs_in_context doesn't get when the iterations are above one.

[XRAY] add get_test_run_iteration method and add more meaningful error raising for incorrect token in XRAY

---

atlassian/bitbucket/cloud/repositories/__init__.py
atlassian/bitbucket/cloud/repositories/refs.py

Didn't see another way to change this so I added this in the two places I tried it, seems to work with pagelen=100.

Add pagelen to bitbucket cloud repositories and branches each functions

---

atlassian/confluence.py

- Adjusted the download logic to process the file content directly as bytes.

fix: [Confluence] download_attachments_from_page: the return value from the response is bytes.

---

atlassian/bitbucket/base.py

The current **created_on** and **completed_on** field of pipeline state is like "2025-03-19T09:55:18.544325754Z" which can not be parsed by datetime.strptime directly
https://github.com/atlassian-api/atlassian-python-api/blob/c2f3382e27bd897b9dc29a3a4ebe1b6926aa84a4/atlassian/bitbucket/base.py#L168

[Bitbucket] keep only 6 digits when using %f in datetime format

---

README.rst
atlassian/jira.py
examples/jira/jira_search_issues_cloud.py

This PR introduces two new functions specifically for Jira Cloud to replace deprecated search APIs:
- Leverages the new `search/jql` REST endpoint with nextPageToken-based pagination.
- Replaces the deprecated search API endpoints (`GET/POST /rest/api/3/search`).
- Supports fetching a limited set or all results based on the batch size parameter.
- **Note:** Atlassian will remove support for the old search API on May 1, 2025.
- Uses the `search/approximate-count` API to retrieve an approximate count of issues for a given JQL query.
- Returns an integer count.
- Added `enhanced_search_issues` to perform nextPageToken-based pagination for Jira Cloud.
- Added `approximate_issue_count` to provide a quick issue count.
- Both functions are decorated with `@cloud_api` to ensure they’re used only …

[JIRA] Add search/jql and search/approximate-count APIs support for Jira Cloud

---

atlassian/confluence.py

Error 
`requests.exceptions.HTTPError: HTTP error occurred while downloading attachments: 404 Client Error: Not Found for url: https://pylaunch.atlassian.net/wiki/https://pylaunch.atlassian.net/wiki/download/attachments/`

Fix 404 error when trying to download attachments from page, multiple hosts

---

.github/workflows/test.yml
atlassian/bitbucket/__init__.py
atlassian/bitbucket/cloud/repositories/repositoryVariables.py
atlassian/confluence.py
atlassian/jira.py
atlassian/rest_client.py
atlassian/typehints.py
examples/jira/jira_review_groups.py
requirements-dev.txt
requirements.txt
tests/test_confluence_advanced_mode.py

Since adding typehints to the entire repo would make for a VERY large PR, I'm breaking up the changes mostly by module.  This PR focuses on adding hints to jira.py

Adding Typehints for jira.py

---

atlassian/bitbucket/cloud/repositories/deploymentEnvironments.py
atlassian/request_utils.py
atlassian/rest_client.py
examples/jira/jira_project_leaders.py
pyproject.toml
requirements-dev.txt
requirements.txt
setup.py

Now that the minimum supported version of Python is 3.9, and Python 2 has been removed, also remove the use of six, since it isn't needed to maintain compatibility.

Remove use of six

---

atlassian/confluence.py

Resolves #991 
Underlying HTTP library supports streaming uploads using file-like objects. So now we just pass `infile` to `attach_content()`

fix(Confluence): method attach_file() to not read() file content

---

atlassian/bitbucket/__init__.py
atlassian/rest_client.py

The title says it #1533 and #1526. 
Greetings,
Raphael

Pass header to request session creation and remove obsolete @property in Bitbucket

---

atlassian/jira.py

This PR fixes the issue of creating URLs for resources from the Agile (Greenhopper) REST API group. The resource URLs were built incorrectly if we used the OAuth2 authorization method when creating a Jira client object.
The problem was that everything worked fine when auth, for example, by username/user_api_token, because, in this case, we could use the “api_root” default value from the Jira client constructor. However, when we use OAuth2, the "api_root" parameter must be overridden. Previously, before the fix, this override did not affect the composition of URLs to the above resources. So, this PR fixes the issue with minimal reformatting, making the code of the corresponding methods more consistent.
This initial issue with the proposal: …

[Jira] Update Agile (Greenhopper) REST API URL handling

---

atlassian/assets.py

Created Assets() class, heavily copied from Insight(). Changed references from Insight to Assets where appropriate. Removed deprecated functions. Replaced iql() with aql() [cloud-only] and navlist_aql() [server-only].

[Assets] Add Assets class

---

examples/jira/jira_add_comment.py

Example for question raised in #1469

chore: add an example to jira_add_comment.py

---

.codeboarding/Atlassian Platform & Marketplace Clients.md
.codeboarding/Bamboo API Client.md
.codeboarding/Bitbucket API Client.md
.codeboarding/Confluence API Client.md
.codeboarding/Jira Ecosystem Clients.md
.codeboarding/REST Client Core.md
.codeboarding/Utility & Error Handling.md
.codeboarding/on_boarding.md

Generated documentation to help new developers to get up to speed with the atlassian-python-api.
Hey all. Me and a friend have noticed that it is quite hard to get to know new codebases, so we are working on something which can help people get up to speed and thus reducing the load for both maintainers and new devs. We believe that it is always best to start with nice high-level visualization and then dig down into the interesting/relevant parts of the code i.e. first task/something one wants to contribute to.
This said, we generated diagrams leveraging static analysis and LLM's.  I generated one for the atlassian-python-api project.
You can see how the added change renders in the github markdown here - https://github.com/CodeBoarding/GeneratedOnBoardings/blob/main/atlassian-python-api/on_ …

Visualization for the atlassian-python-api codebase

---

docs/jira.rst

Found on [readthedocs](https://atlassian-python-api.readthedocs.io/jira.html) that the method _jira.get_issue_tree_ does not work. Use _get_issue_tree_recursive_ instead. In this regard, I decided to try updating the documentation. I suppose that the edit in the source will also correct the information on readthedocs. Is it right? 🤔

[Doc] [Jira] Update info about jira.get_issue_tree_recursive method

---

atlassian/confluence/__init__.py

Previously, there was a great lack of a method for adding space permissions to a space

Update confluence/__init__.py with add space permissions
